/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 * 
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Data In Motion Consulting - initial implementation
 */
package org.eclipse.fennec.model.gdprReport;


import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.fennec.emf.osgi.annotation.provide.EPackage;

import org.osgi.annotation.versioning.ProviderType;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each operation of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.eclipse.fennec.model.gdprReport.GDPRReportFactory
 * @model kind="package"
 *        annotation="Version value='1.0'"
 *        annotation="http://www.eclipse.org/emf/2002/GenModel complianceLevel='21.0' oSGiCompatible='true' basePackage='org.eclipse.fennec.model' resource='XMI' copyrightText='Copyright (c) 2026 Contributors to the Eclipse Foundation.\n\nThis program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/\n\nSPDX-License-Identifier: EPL-2.0\n\nContributors:\n  Data In Motion Consulting - initial implementation'"
 * @generated
 */
@ProviderType
@EPackage(uri = GDPRReportPackage.eNS_URI, fingerprint = "fp1:698d60694fccada712d46721416328a5bbbe62fe5a45ef97ee44a3fe578d96ae", genModel = "/model/gdpr-report.genmodel", genModelSourceLocations = {"model/gdpr-report.genmodel","org.eclipse.fennec.gdpr.report.model/model/gdpr-report.genmodel"}, ecore = "/model/gdpr-report.ecore", ecoreSourceLocations = "/model/gdpr-report.ecore")
public interface GDPRReportPackage extends org.eclipse.emf.ecore.EPackage {
	/**
	 * The package name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNAME = "gdprReport";

	/**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_URI = "https://org.eclipse/fennec/gdpr-report/1.0.0";

	/**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_PREFIX = "gdpr-report";

	/**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	GDPRReportPackage eINSTANCE = org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl.init();

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.impl.GdprReportImpl <em>Gdpr Report</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.impl.GdprReportImpl
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getGdprReport()
	 * @generated
	 */
	int GDPR_REPORT = 0;

	/**
	 * The feature id for the '<em><b>Report Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REPORT__REPORT_ID = 0;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REPORT__NAME = 1;

	/**
	 * The feature id for the '<em><b>Generated At</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REPORT__GENERATED_AT = 2;

	/**
	 * The feature id for the '<em><b>Generated By</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REPORT__GENERATED_BY = 3;

	/**
	 * The feature id for the '<em><b>Subject</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REPORT__SUBJECT = 4;

	/**
	 * The feature id for the '<em><b>Corpus</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REPORT__CORPUS = 5;

	/**
	 * The feature id for the '<em><b>Classifier Evaluation</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REPORT__CLASSIFIER_EVALUATION = 6;

	/**
	 * The feature id for the '<em><b>Combinations</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REPORT__COMBINATIONS = 7;

	/**
	 * The feature id for the '<em><b>Disclaimer</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REPORT__DISCLAIMER = 8;

	/**
	 * The feature id for the '<em><b>Origin</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REPORT__ORIGIN = 9;

	/**
	 * The number of structural features of the '<em>Gdpr Report</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REPORT_FEATURE_COUNT = 10;

	/**
	 * The number of operations of the '<em>Gdpr Report</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REPORT_OPERATION_COUNT = 0;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.impl.SubjectModelImpl <em>Subject Model</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.impl.SubjectModelImpl
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getSubjectModel()
	 * @generated
	 */
	int SUBJECT_MODEL = 1;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SUBJECT_MODEL__NAME = 0;

	/**
	 * The feature id for the '<em><b>Ns URI</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SUBJECT_MODEL__NS_URI = 1;

	/**
	 * The feature id for the '<em><b>Ns Prefix</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SUBJECT_MODEL__NS_PREFIX = 2;

	/**
	 * The feature id for the '<em><b>Model Fingerprint</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SUBJECT_MODEL__MODEL_FINGERPRINT = 3;

	/**
	 * The number of structural features of the '<em>Subject Model</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SUBJECT_MODEL_FEATURE_COUNT = 4;

	/**
	 * The number of operations of the '<em>Subject Model</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SUBJECT_MODEL_OPERATION_COUNT = 0;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.impl.LegalCorpusRefImpl <em>Legal Corpus Ref</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.impl.LegalCorpusRefImpl
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getLegalCorpusRef()
	 * @generated
	 */
	int LEGAL_CORPUS_REF = 2;

	/**
	 * The feature id for the '<em><b>Celex</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LEGAL_CORPUS_REF__CELEX = 0;

	/**
	 * The feature id for the '<em><b>Consolidated Date</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LEGAL_CORPUS_REF__CONSOLIDATED_DATE = 1;

	/**
	 * The feature id for the '<em><b>Language</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LEGAL_CORPUS_REF__LANGUAGE = 2;

	/**
	 * The feature id for the '<em><b>Formex Schema</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LEGAL_CORPUS_REF__FORMEX_SCHEMA = 3;

	/**
	 * The number of structural features of the '<em>Legal Corpus Ref</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LEGAL_CORPUS_REF_FEATURE_COUNT = 4;

	/**
	 * The number of operations of the '<em>Legal Corpus Ref</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LEGAL_CORPUS_REF_OPERATION_COUNT = 0;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.impl.ClassifierEvaluationImpl <em>Classifier Evaluation</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.impl.ClassifierEvaluationImpl
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getClassifierEvaluation()
	 * @generated
	 */
	int CLASSIFIER_EVALUATION = 3;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CLASSIFIER_EVALUATION__ID = 0;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CLASSIFIER_EVALUATION__NAME = 1;

	/**
	 * The feature id for the '<em><b>Uri Fragment</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CLASSIFIER_EVALUATION__URI_FRAGMENT = 2;

	/**
	 * The feature id for the '<em><b>Feature Evaluation</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CLASSIFIER_EVALUATION__FEATURE_EVALUATION = 3;

	/**
	 * The feature id for the '<em><b>Findings</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CLASSIFIER_EVALUATION__FINDINGS = 4;

	/**
	 * The number of structural features of the '<em>Classifier Evaluation</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CLASSIFIER_EVALUATION_FEATURE_COUNT = 5;

	/**
	 * The number of operations of the '<em>Classifier Evaluation</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CLASSIFIER_EVALUATION_OPERATION_COUNT = 0;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.impl.FeatureEvaluationImpl <em>Feature Evaluation</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.impl.FeatureEvaluationImpl
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getFeatureEvaluation()
	 * @generated
	 */
	int FEATURE_EVALUATION = 4;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FEATURE_EVALUATION__ID = 0;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FEATURE_EVALUATION__NAME = 1;

	/**
	 * The feature id for the '<em><b>Uri Fragment</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FEATURE_EVALUATION__URI_FRAGMENT = 2;

	/**
	 * The feature id for the '<em><b>Type Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FEATURE_EVALUATION__TYPE_NAME = 3;

	/**
	 * The feature id for the '<em><b>Many</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FEATURE_EVALUATION__MANY = 4;

	/**
	 * The feature id for the '<em><b>Relevance Level</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FEATURE_EVALUATION__RELEVANCE_LEVEL = 5;

	/**
	 * The feature id for the '<em><b>Findings</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FEATURE_EVALUATION__FINDINGS = 6;

	/**
	 * The feature id for the '<em><b>Part Of Combinations</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FEATURE_EVALUATION__PART_OF_COMBINATIONS = 7;

	/**
	 * The feature id for the '<em><b>Purpose</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FEATURE_EVALUATION__PURPOSE = 8;

	/**
	 * The number of structural features of the '<em>Feature Evaluation</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FEATURE_EVALUATION_FEATURE_COUNT = 9;

	/**
	 * The number of operations of the '<em>Feature Evaluation</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FEATURE_EVALUATION_OPERATION_COUNT = 0;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.impl.FindingImpl <em>Finding</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.impl.FindingImpl
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getFinding()
	 * @generated
	 */
	int FINDING = 5;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINDING__ID = 0;

	/**
	 * The feature id for the '<em><b>Category</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINDING__CATEGORY = 1;

	/**
	 * The feature id for the '<em><b>Relevance Level</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINDING__RELEVANCE_LEVEL = 2;

	/**
	 * The feature id for the '<em><b>Confidence</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINDING__CONFIDENCE = 3;

	/**
	 * The feature id for the '<em><b>Detected By</b></em>' attribute list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINDING__DETECTED_BY = 4;

	/**
	 * The feature id for the '<em><b>Signal Values</b></em>' attribute list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINDING__SIGNAL_VALUES = 5;

	/**
	 * The feature id for the '<em><b>Rationale</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINDING__RATIONALE = 6;

	/**
	 * The feature id for the '<em><b>Recommendation</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINDING__RECOMMENDATION = 7;

	/**
	 * The feature id for the '<em><b>Evidence</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINDING__EVIDENCE = 8;

	/**
	 * The number of structural features of the '<em>Finding</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINDING_FEATURE_COUNT = 9;

	/**
	 * The number of operations of the '<em>Finding</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FINDING_OPERATION_COUNT = 0;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.impl.CombinationFindingImpl <em>Combination Finding</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.impl.CombinationFindingImpl
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getCombinationFinding()
	 * @generated
	 */
	int COMBINATION_FINDING = 6;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMBINATION_FINDING__ID = FINDING__ID;

	/**
	 * The feature id for the '<em><b>Category</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMBINATION_FINDING__CATEGORY = FINDING__CATEGORY;

	/**
	 * The feature id for the '<em><b>Relevance Level</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMBINATION_FINDING__RELEVANCE_LEVEL = FINDING__RELEVANCE_LEVEL;

	/**
	 * The feature id for the '<em><b>Confidence</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMBINATION_FINDING__CONFIDENCE = FINDING__CONFIDENCE;

	/**
	 * The feature id for the '<em><b>Detected By</b></em>' attribute list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMBINATION_FINDING__DETECTED_BY = FINDING__DETECTED_BY;

	/**
	 * The feature id for the '<em><b>Signal Values</b></em>' attribute list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMBINATION_FINDING__SIGNAL_VALUES = FINDING__SIGNAL_VALUES;

	/**
	 * The feature id for the '<em><b>Rationale</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMBINATION_FINDING__RATIONALE = FINDING__RATIONALE;

	/**
	 * The feature id for the '<em><b>Recommendation</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMBINATION_FINDING__RECOMMENDATION = FINDING__RECOMMENDATION;

	/**
	 * The feature id for the '<em><b>Evidence</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMBINATION_FINDING__EVIDENCE = FINDING__EVIDENCE;

	/**
	 * The feature id for the '<em><b>Combination Kind</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMBINATION_FINDING__COMBINATION_KIND = FINDING_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Features</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMBINATION_FINDING__FEATURES = FINDING_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Combination Finding</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMBINATION_FINDING_FEATURE_COUNT = FINDING_FEATURE_COUNT + 2;

	/**
	 * The number of operations of the '<em>Combination Finding</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMBINATION_FINDING_OPERATION_COUNT = FINDING_OPERATION_COUNT + 0;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.impl.EvidenceImpl <em>Evidence</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.impl.EvidenceImpl
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getEvidence()
	 * @generated
	 */
	int EVIDENCE = 7;

	/**
	 * The feature id for the '<em><b>Citation Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EVIDENCE__CITATION_ID = 0;

	/**
	 * The feature id for the '<em><b>Quote</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EVIDENCE__QUOTE = 1;

	/**
	 * The feature id for the '<em><b>Verbatim</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EVIDENCE__VERBATIM = 2;

	/**
	 * The feature id for the '<em><b>Relevance</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EVIDENCE__RELEVANCE = 3;

	/**
	 * The feature id for the '<em><b>Source Ref</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EVIDENCE__SOURCE_REF = 4;

	/**
	 * The number of structural features of the '<em>Evidence</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EVIDENCE_FEATURE_COUNT = 5;

	/**
	 * The number of operations of the '<em>Evidence</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EVIDENCE_OPERATION_COUNT = 0;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.impl.GdprRequestStatusImpl <em>Gdpr Request Status</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.impl.GdprRequestStatusImpl
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getGdprRequestStatus()
	 * @generated
	 */
	int GDPR_REQUEST_STATUS = 8;

	/**
	 * The feature id for the '<em><b>Model Fingerprint</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REQUEST_STATUS__MODEL_FINGERPRINT = 0;

	/**
	 * The feature id for the '<em><b>Ns URI</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REQUEST_STATUS__NS_URI = 1;

	/**
	 * The feature id for the '<em><b>Batch Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REQUEST_STATUS__BATCH_ID = 2;

	/**
	 * The feature id for the '<em><b>Custom Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REQUEST_STATUS__CUSTOM_ID = 3;

	/**
	 * The feature id for the '<em><b>Report Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REQUEST_STATUS__REPORT_ID = 4;

	/**
	 * The feature id for the '<em><b>Status</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REQUEST_STATUS__STATUS = 5;

	/**
	 * The feature id for the '<em><b>Submitted At</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REQUEST_STATUS__SUBMITTED_AT = 6;

	/**
	 * The feature id for the '<em><b>Ended At</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REQUEST_STATUS__ENDED_AT = 7;

	/**
	 * The feature id for the '<em><b>Message</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REQUEST_STATUS__MESSAGE = 8;

	/**
	 * The feature id for the '<em><b>Continuation Count</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REQUEST_STATUS__CONTINUATION_COUNT = 9;

	/**
	 * The feature id for the '<em><b>Output Tokens</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REQUEST_STATUS__OUTPUT_TOKENS = 10;

	/**
	 * The number of structural features of the '<em>Gdpr Request Status</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REQUEST_STATUS_FEATURE_COUNT = 11;

	/**
	 * The number of operations of the '<em>Gdpr Request Status</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GDPR_REQUEST_STATUS_OPERATION_COUNT = 0;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.DataCategory <em>Data Category</em>}' enum.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.DataCategory
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getDataCategory()
	 * @generated
	 */
	int DATA_CATEGORY = 9;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.RelevanceLevelType <em>Relevance Level Type</em>}' enum.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.RelevanceLevelType
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getRelevanceLevelType()
	 * @generated
	 */
	int RELEVANCE_LEVEL_TYPE = 10;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.ConfidenceType <em>Confidence Type</em>}' enum.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.ConfidenceType
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getConfidenceType()
	 * @generated
	 */
	int CONFIDENCE_TYPE = 11;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.DetectionSignal <em>Detection Signal</em>}' enum.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.DetectionSignal
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getDetectionSignal()
	 * @generated
	 */
	int DETECTION_SIGNAL = 12;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.CombinationKind <em>Combination Kind</em>}' enum.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.CombinationKind
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getCombinationKind()
	 * @generated
	 */
	int COMBINATION_KIND = 13;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.RequestStatusType <em>Request Status Type</em>}' enum.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.RequestStatusType
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getRequestStatusType()
	 * @generated
	 */
	int REQUEST_STATUS_TYPE = 14;

	/**
	 * The meta object id for the '{@link org.eclipse.fennec.model.gdprReport.GdprReportOrigin <em>Gdpr Report Origin</em>}' enum.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.fennec.model.gdprReport.GdprReportOrigin
	 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getGdprReportOrigin()
	 * @generated
	 */
	int GDPR_REPORT_ORIGIN = 15;


	/**
	 * Returns the meta object for class '{@link org.eclipse.fennec.model.gdprReport.GdprReport <em>Gdpr Report</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Gdpr Report</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprReport
	 * @generated
	 */
	EClass getGdprReport();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getReportId <em>Report Id</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Report Id</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprReport#getReportId()
	 * @see #getGdprReport()
	 * @generated
	 */
	EAttribute getGdprReport_ReportId();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprReport#getName()
	 * @see #getGdprReport()
	 * @generated
	 */
	EAttribute getGdprReport_Name();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getGeneratedAt <em>Generated At</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Generated At</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprReport#getGeneratedAt()
	 * @see #getGdprReport()
	 * @generated
	 */
	EAttribute getGdprReport_GeneratedAt();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getGeneratedBy <em>Generated By</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Generated By</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprReport#getGeneratedBy()
	 * @see #getGdprReport()
	 * @generated
	 */
	EAttribute getGdprReport_GeneratedBy();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getSubject <em>Subject</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Subject</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprReport#getSubject()
	 * @see #getGdprReport()
	 * @generated
	 */
	EReference getGdprReport_Subject();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getCorpus <em>Corpus</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Corpus</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprReport#getCorpus()
	 * @see #getGdprReport()
	 * @generated
	 */
	EReference getGdprReport_Corpus();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getClassifierEvaluation <em>Classifier Evaluation</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Classifier Evaluation</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprReport#getClassifierEvaluation()
	 * @see #getGdprReport()
	 * @generated
	 */
	EReference getGdprReport_ClassifierEvaluation();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getCombinations <em>Combinations</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Combinations</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprReport#getCombinations()
	 * @see #getGdprReport()
	 * @generated
	 */
	EReference getGdprReport_Combinations();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getDisclaimer <em>Disclaimer</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Disclaimer</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprReport#getDisclaimer()
	 * @see #getGdprReport()
	 * @generated
	 */
	EAttribute getGdprReport_Disclaimer();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getOrigin <em>Origin</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Origin</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprReport#getOrigin()
	 * @see #getGdprReport()
	 * @generated
	 */
	EAttribute getGdprReport_Origin();

	/**
	 * Returns the meta object for class '{@link org.eclipse.fennec.model.gdprReport.SubjectModel <em>Subject Model</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Subject Model</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.SubjectModel
	 * @generated
	 */
	EClass getSubjectModel();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.SubjectModel#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.SubjectModel#getName()
	 * @see #getSubjectModel()
	 * @generated
	 */
	EAttribute getSubjectModel_Name();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.SubjectModel#getNsURI <em>Ns URI</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Ns URI</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.SubjectModel#getNsURI()
	 * @see #getSubjectModel()
	 * @generated
	 */
	EAttribute getSubjectModel_NsURI();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.SubjectModel#getNsPrefix <em>Ns Prefix</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Ns Prefix</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.SubjectModel#getNsPrefix()
	 * @see #getSubjectModel()
	 * @generated
	 */
	EAttribute getSubjectModel_NsPrefix();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.SubjectModel#getModelFingerprint <em>Model Fingerprint</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Model Fingerprint</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.SubjectModel#getModelFingerprint()
	 * @see #getSubjectModel()
	 * @generated
	 */
	EAttribute getSubjectModel_ModelFingerprint();

	/**
	 * Returns the meta object for class '{@link org.eclipse.fennec.model.gdprReport.LegalCorpusRef <em>Legal Corpus Ref</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Legal Corpus Ref</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.LegalCorpusRef
	 * @generated
	 */
	EClass getLegalCorpusRef();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.LegalCorpusRef#getCelex <em>Celex</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Celex</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.LegalCorpusRef#getCelex()
	 * @see #getLegalCorpusRef()
	 * @generated
	 */
	EAttribute getLegalCorpusRef_Celex();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.LegalCorpusRef#getConsolidatedDate <em>Consolidated Date</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Consolidated Date</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.LegalCorpusRef#getConsolidatedDate()
	 * @see #getLegalCorpusRef()
	 * @generated
	 */
	EAttribute getLegalCorpusRef_ConsolidatedDate();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.LegalCorpusRef#getLanguage <em>Language</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Language</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.LegalCorpusRef#getLanguage()
	 * @see #getLegalCorpusRef()
	 * @generated
	 */
	EAttribute getLegalCorpusRef_Language();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.LegalCorpusRef#getFormexSchema <em>Formex Schema</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Formex Schema</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.LegalCorpusRef#getFormexSchema()
	 * @see #getLegalCorpusRef()
	 * @generated
	 */
	EAttribute getLegalCorpusRef_FormexSchema();

	/**
	 * Returns the meta object for class '{@link org.eclipse.fennec.model.gdprReport.ClassifierEvaluation <em>Classifier Evaluation</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Classifier Evaluation</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.ClassifierEvaluation
	 * @generated
	 */
	EClass getClassifierEvaluation();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.ClassifierEvaluation#getId <em>Id</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Id</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.ClassifierEvaluation#getId()
	 * @see #getClassifierEvaluation()
	 * @generated
	 */
	EAttribute getClassifierEvaluation_Id();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.ClassifierEvaluation#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.ClassifierEvaluation#getName()
	 * @see #getClassifierEvaluation()
	 * @generated
	 */
	EAttribute getClassifierEvaluation_Name();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.ClassifierEvaluation#getUriFragment <em>Uri Fragment</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Uri Fragment</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.ClassifierEvaluation#getUriFragment()
	 * @see #getClassifierEvaluation()
	 * @generated
	 */
	EAttribute getClassifierEvaluation_UriFragment();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.fennec.model.gdprReport.ClassifierEvaluation#getFeatureEvaluation <em>Feature Evaluation</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Feature Evaluation</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.ClassifierEvaluation#getFeatureEvaluation()
	 * @see #getClassifierEvaluation()
	 * @generated
	 */
	EReference getClassifierEvaluation_FeatureEvaluation();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.fennec.model.gdprReport.ClassifierEvaluation#getFindings <em>Findings</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Findings</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.ClassifierEvaluation#getFindings()
	 * @see #getClassifierEvaluation()
	 * @generated
	 */
	EReference getClassifierEvaluation_Findings();

	/**
	 * Returns the meta object for class '{@link org.eclipse.fennec.model.gdprReport.FeatureEvaluation <em>Feature Evaluation</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Feature Evaluation</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.FeatureEvaluation
	 * @generated
	 */
	EClass getFeatureEvaluation();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getId <em>Id</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Id</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getId()
	 * @see #getFeatureEvaluation()
	 * @generated
	 */
	EAttribute getFeatureEvaluation_Id();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getName()
	 * @see #getFeatureEvaluation()
	 * @generated
	 */
	EAttribute getFeatureEvaluation_Name();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getUriFragment <em>Uri Fragment</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Uri Fragment</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getUriFragment()
	 * @see #getFeatureEvaluation()
	 * @generated
	 */
	EAttribute getFeatureEvaluation_UriFragment();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getTypeName <em>Type Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Type Name</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getTypeName()
	 * @see #getFeatureEvaluation()
	 * @generated
	 */
	EAttribute getFeatureEvaluation_TypeName();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.FeatureEvaluation#isMany <em>Many</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Many</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.FeatureEvaluation#isMany()
	 * @see #getFeatureEvaluation()
	 * @generated
	 */
	EAttribute getFeatureEvaluation_Many();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getRelevanceLevel <em>Relevance Level</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Relevance Level</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getRelevanceLevel()
	 * @see #getFeatureEvaluation()
	 * @generated
	 */
	EAttribute getFeatureEvaluation_RelevanceLevel();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getFindings <em>Findings</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Findings</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getFindings()
	 * @see #getFeatureEvaluation()
	 * @generated
	 */
	EReference getFeatureEvaluation_Findings();

	/**
	 * Returns the meta object for the reference list '{@link org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getPartOfCombinations <em>Part Of Combinations</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference list '<em>Part Of Combinations</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getPartOfCombinations()
	 * @see #getFeatureEvaluation()
	 * @generated
	 */
	EReference getFeatureEvaluation_PartOfCombinations();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getPurpose <em>Purpose</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Purpose</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.FeatureEvaluation#getPurpose()
	 * @see #getFeatureEvaluation()
	 * @generated
	 */
	EAttribute getFeatureEvaluation_Purpose();

	/**
	 * Returns the meta object for class '{@link org.eclipse.fennec.model.gdprReport.Finding <em>Finding</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Finding</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Finding
	 * @generated
	 */
	EClass getFinding();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.Finding#getId <em>Id</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Id</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Finding#getId()
	 * @see #getFinding()
	 * @generated
	 */
	EAttribute getFinding_Id();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.Finding#getCategory <em>Category</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Category</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Finding#getCategory()
	 * @see #getFinding()
	 * @generated
	 */
	EAttribute getFinding_Category();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.Finding#getRelevanceLevel <em>Relevance Level</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Relevance Level</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Finding#getRelevanceLevel()
	 * @see #getFinding()
	 * @generated
	 */
	EAttribute getFinding_RelevanceLevel();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.Finding#getConfidence <em>Confidence</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Confidence</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Finding#getConfidence()
	 * @see #getFinding()
	 * @generated
	 */
	EAttribute getFinding_Confidence();

	/**
	 * Returns the meta object for the attribute list '{@link org.eclipse.fennec.model.gdprReport.Finding#getDetectedBy <em>Detected By</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute list '<em>Detected By</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Finding#getDetectedBy()
	 * @see #getFinding()
	 * @generated
	 */
	EAttribute getFinding_DetectedBy();

	/**
	 * Returns the meta object for the attribute list '{@link org.eclipse.fennec.model.gdprReport.Finding#getSignalValues <em>Signal Values</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute list '<em>Signal Values</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Finding#getSignalValues()
	 * @see #getFinding()
	 * @generated
	 */
	EAttribute getFinding_SignalValues();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.Finding#getRationale <em>Rationale</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Rationale</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Finding#getRationale()
	 * @see #getFinding()
	 * @generated
	 */
	EAttribute getFinding_Rationale();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.Finding#getRecommendation <em>Recommendation</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Recommendation</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Finding#getRecommendation()
	 * @see #getFinding()
	 * @generated
	 */
	EAttribute getFinding_Recommendation();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.fennec.model.gdprReport.Finding#getEvidence <em>Evidence</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Evidence</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Finding#getEvidence()
	 * @see #getFinding()
	 * @generated
	 */
	EReference getFinding_Evidence();

	/**
	 * Returns the meta object for class '{@link org.eclipse.fennec.model.gdprReport.CombinationFinding <em>Combination Finding</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Combination Finding</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.CombinationFinding
	 * @generated
	 */
	EClass getCombinationFinding();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.CombinationFinding#getCombinationKind <em>Combination Kind</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Combination Kind</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.CombinationFinding#getCombinationKind()
	 * @see #getCombinationFinding()
	 * @generated
	 */
	EAttribute getCombinationFinding_CombinationKind();

	/**
	 * Returns the meta object for the reference list '{@link org.eclipse.fennec.model.gdprReport.CombinationFinding#getFeatures <em>Features</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference list '<em>Features</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.CombinationFinding#getFeatures()
	 * @see #getCombinationFinding()
	 * @generated
	 */
	EReference getCombinationFinding_Features();

	/**
	 * Returns the meta object for class '{@link org.eclipse.fennec.model.gdprReport.Evidence <em>Evidence</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Evidence</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Evidence
	 * @generated
	 */
	EClass getEvidence();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.Evidence#getCitationId <em>Citation Id</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Citation Id</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Evidence#getCitationId()
	 * @see #getEvidence()
	 * @generated
	 */
	EAttribute getEvidence_CitationId();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.Evidence#getQuote <em>Quote</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Quote</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Evidence#getQuote()
	 * @see #getEvidence()
	 * @generated
	 */
	EAttribute getEvidence_Quote();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.Evidence#isVerbatim <em>Verbatim</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Verbatim</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Evidence#isVerbatim()
	 * @see #getEvidence()
	 * @generated
	 */
	EAttribute getEvidence_Verbatim();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.Evidence#getRelevance <em>Relevance</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Relevance</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Evidence#getRelevance()
	 * @see #getEvidence()
	 * @generated
	 */
	EAttribute getEvidence_Relevance();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.Evidence#getSourceRef <em>Source Ref</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Source Ref</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.Evidence#getSourceRef()
	 * @see #getEvidence()
	 * @generated
	 */
	EAttribute getEvidence_SourceRef();

	/**
	 * Returns the meta object for class '{@link org.eclipse.fennec.model.gdprReport.GdprRequestStatus <em>Gdpr Request Status</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Gdpr Request Status</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprRequestStatus
	 * @generated
	 */
	EClass getGdprRequestStatus();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getModelFingerprint <em>Model Fingerprint</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Model Fingerprint</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getModelFingerprint()
	 * @see #getGdprRequestStatus()
	 * @generated
	 */
	EAttribute getGdprRequestStatus_ModelFingerprint();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getNsURI <em>Ns URI</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Ns URI</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getNsURI()
	 * @see #getGdprRequestStatus()
	 * @generated
	 */
	EAttribute getGdprRequestStatus_NsURI();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getBatchId <em>Batch Id</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Batch Id</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getBatchId()
	 * @see #getGdprRequestStatus()
	 * @generated
	 */
	EAttribute getGdprRequestStatus_BatchId();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getCustomId <em>Custom Id</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Custom Id</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getCustomId()
	 * @see #getGdprRequestStatus()
	 * @generated
	 */
	EAttribute getGdprRequestStatus_CustomId();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getReportId <em>Report Id</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Report Id</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getReportId()
	 * @see #getGdprRequestStatus()
	 * @generated
	 */
	EAttribute getGdprRequestStatus_ReportId();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getStatus <em>Status</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Status</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getStatus()
	 * @see #getGdprRequestStatus()
	 * @generated
	 */
	EAttribute getGdprRequestStatus_Status();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getSubmittedAt <em>Submitted At</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Submitted At</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getSubmittedAt()
	 * @see #getGdprRequestStatus()
	 * @generated
	 */
	EAttribute getGdprRequestStatus_SubmittedAt();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getEndedAt <em>Ended At</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Ended At</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getEndedAt()
	 * @see #getGdprRequestStatus()
	 * @generated
	 */
	EAttribute getGdprRequestStatus_EndedAt();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getMessage <em>Message</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Message</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getMessage()
	 * @see #getGdprRequestStatus()
	 * @generated
	 */
	EAttribute getGdprRequestStatus_Message();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getContinuationCount <em>Continuation Count</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Continuation Count</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getContinuationCount()
	 * @see #getGdprRequestStatus()
	 * @generated
	 */
	EAttribute getGdprRequestStatus_ContinuationCount();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getOutputTokens <em>Output Tokens</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Output Tokens</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprRequestStatus#getOutputTokens()
	 * @see #getGdprRequestStatus()
	 * @generated
	 */
	EAttribute getGdprRequestStatus_OutputTokens();

	/**
	 * Returns the meta object for enum '{@link org.eclipse.fennec.model.gdprReport.DataCategory <em>Data Category</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Data Category</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.DataCategory
	 * @generated
	 */
	EEnum getDataCategory();

	/**
	 * Returns the meta object for enum '{@link org.eclipse.fennec.model.gdprReport.RelevanceLevelType <em>Relevance Level Type</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Relevance Level Type</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.RelevanceLevelType
	 * @generated
	 */
	EEnum getRelevanceLevelType();

	/**
	 * Returns the meta object for enum '{@link org.eclipse.fennec.model.gdprReport.ConfidenceType <em>Confidence Type</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Confidence Type</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.ConfidenceType
	 * @generated
	 */
	EEnum getConfidenceType();

	/**
	 * Returns the meta object for enum '{@link org.eclipse.fennec.model.gdprReport.DetectionSignal <em>Detection Signal</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Detection Signal</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.DetectionSignal
	 * @generated
	 */
	EEnum getDetectionSignal();

	/**
	 * Returns the meta object for enum '{@link org.eclipse.fennec.model.gdprReport.CombinationKind <em>Combination Kind</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Combination Kind</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.CombinationKind
	 * @generated
	 */
	EEnum getCombinationKind();

	/**
	 * Returns the meta object for enum '{@link org.eclipse.fennec.model.gdprReport.RequestStatusType <em>Request Status Type</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Request Status Type</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.RequestStatusType
	 * @generated
	 */
	EEnum getRequestStatusType();

	/**
	 * Returns the meta object for enum '{@link org.eclipse.fennec.model.gdprReport.GdprReportOrigin <em>Gdpr Report Origin</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Gdpr Report Origin</em>'.
	 * @see org.eclipse.fennec.model.gdprReport.GdprReportOrigin
	 * @generated
	 */
	EEnum getGdprReportOrigin();

	/**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
	GDPRReportFactory getGDPRReportFactory();

	/**
	 * <!-- begin-user-doc -->
	 * Defines literals for the meta objects that represent
	 * <ul>
	 *   <li>each class,</li>
	 *   <li>each feature of each class,</li>
	 *   <li>each operation of each class,</li>
	 *   <li>each enum,</li>
	 *   <li>and each data type</li>
	 * </ul>
	 * <!-- end-user-doc -->
	 * @generated
	 */
	interface Literals {
		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.impl.GdprReportImpl <em>Gdpr Report</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.impl.GdprReportImpl
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getGdprReport()
		 * @generated
		 */
		EClass GDPR_REPORT = eINSTANCE.getGdprReport();

		/**
		 * The meta object literal for the '<em><b>Report Id</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REPORT__REPORT_ID = eINSTANCE.getGdprReport_ReportId();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REPORT__NAME = eINSTANCE.getGdprReport_Name();

		/**
		 * The meta object literal for the '<em><b>Generated At</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REPORT__GENERATED_AT = eINSTANCE.getGdprReport_GeneratedAt();

		/**
		 * The meta object literal for the '<em><b>Generated By</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REPORT__GENERATED_BY = eINSTANCE.getGdprReport_GeneratedBy();

		/**
		 * The meta object literal for the '<em><b>Subject</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference GDPR_REPORT__SUBJECT = eINSTANCE.getGdprReport_Subject();

		/**
		 * The meta object literal for the '<em><b>Corpus</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference GDPR_REPORT__CORPUS = eINSTANCE.getGdprReport_Corpus();

		/**
		 * The meta object literal for the '<em><b>Classifier Evaluation</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference GDPR_REPORT__CLASSIFIER_EVALUATION = eINSTANCE.getGdprReport_ClassifierEvaluation();

		/**
		 * The meta object literal for the '<em><b>Combinations</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference GDPR_REPORT__COMBINATIONS = eINSTANCE.getGdprReport_Combinations();

		/**
		 * The meta object literal for the '<em><b>Disclaimer</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REPORT__DISCLAIMER = eINSTANCE.getGdprReport_Disclaimer();

		/**
		 * The meta object literal for the '<em><b>Origin</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REPORT__ORIGIN = eINSTANCE.getGdprReport_Origin();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.impl.SubjectModelImpl <em>Subject Model</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.impl.SubjectModelImpl
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getSubjectModel()
		 * @generated
		 */
		EClass SUBJECT_MODEL = eINSTANCE.getSubjectModel();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SUBJECT_MODEL__NAME = eINSTANCE.getSubjectModel_Name();

		/**
		 * The meta object literal for the '<em><b>Ns URI</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SUBJECT_MODEL__NS_URI = eINSTANCE.getSubjectModel_NsURI();

		/**
		 * The meta object literal for the '<em><b>Ns Prefix</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SUBJECT_MODEL__NS_PREFIX = eINSTANCE.getSubjectModel_NsPrefix();

		/**
		 * The meta object literal for the '<em><b>Model Fingerprint</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SUBJECT_MODEL__MODEL_FINGERPRINT = eINSTANCE.getSubjectModel_ModelFingerprint();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.impl.LegalCorpusRefImpl <em>Legal Corpus Ref</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.impl.LegalCorpusRefImpl
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getLegalCorpusRef()
		 * @generated
		 */
		EClass LEGAL_CORPUS_REF = eINSTANCE.getLegalCorpusRef();

		/**
		 * The meta object literal for the '<em><b>Celex</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute LEGAL_CORPUS_REF__CELEX = eINSTANCE.getLegalCorpusRef_Celex();

		/**
		 * The meta object literal for the '<em><b>Consolidated Date</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute LEGAL_CORPUS_REF__CONSOLIDATED_DATE = eINSTANCE.getLegalCorpusRef_ConsolidatedDate();

		/**
		 * The meta object literal for the '<em><b>Language</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute LEGAL_CORPUS_REF__LANGUAGE = eINSTANCE.getLegalCorpusRef_Language();

		/**
		 * The meta object literal for the '<em><b>Formex Schema</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute LEGAL_CORPUS_REF__FORMEX_SCHEMA = eINSTANCE.getLegalCorpusRef_FormexSchema();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.impl.ClassifierEvaluationImpl <em>Classifier Evaluation</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.impl.ClassifierEvaluationImpl
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getClassifierEvaluation()
		 * @generated
		 */
		EClass CLASSIFIER_EVALUATION = eINSTANCE.getClassifierEvaluation();

		/**
		 * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute CLASSIFIER_EVALUATION__ID = eINSTANCE.getClassifierEvaluation_Id();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute CLASSIFIER_EVALUATION__NAME = eINSTANCE.getClassifierEvaluation_Name();

		/**
		 * The meta object literal for the '<em><b>Uri Fragment</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute CLASSIFIER_EVALUATION__URI_FRAGMENT = eINSTANCE.getClassifierEvaluation_UriFragment();

		/**
		 * The meta object literal for the '<em><b>Feature Evaluation</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference CLASSIFIER_EVALUATION__FEATURE_EVALUATION = eINSTANCE.getClassifierEvaluation_FeatureEvaluation();

		/**
		 * The meta object literal for the '<em><b>Findings</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference CLASSIFIER_EVALUATION__FINDINGS = eINSTANCE.getClassifierEvaluation_Findings();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.impl.FeatureEvaluationImpl <em>Feature Evaluation</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.impl.FeatureEvaluationImpl
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getFeatureEvaluation()
		 * @generated
		 */
		EClass FEATURE_EVALUATION = eINSTANCE.getFeatureEvaluation();

		/**
		 * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FEATURE_EVALUATION__ID = eINSTANCE.getFeatureEvaluation_Id();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FEATURE_EVALUATION__NAME = eINSTANCE.getFeatureEvaluation_Name();

		/**
		 * The meta object literal for the '<em><b>Uri Fragment</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FEATURE_EVALUATION__URI_FRAGMENT = eINSTANCE.getFeatureEvaluation_UriFragment();

		/**
		 * The meta object literal for the '<em><b>Type Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FEATURE_EVALUATION__TYPE_NAME = eINSTANCE.getFeatureEvaluation_TypeName();

		/**
		 * The meta object literal for the '<em><b>Many</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FEATURE_EVALUATION__MANY = eINSTANCE.getFeatureEvaluation_Many();

		/**
		 * The meta object literal for the '<em><b>Relevance Level</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FEATURE_EVALUATION__RELEVANCE_LEVEL = eINSTANCE.getFeatureEvaluation_RelevanceLevel();

		/**
		 * The meta object literal for the '<em><b>Findings</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference FEATURE_EVALUATION__FINDINGS = eINSTANCE.getFeatureEvaluation_Findings();

		/**
		 * The meta object literal for the '<em><b>Part Of Combinations</b></em>' reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference FEATURE_EVALUATION__PART_OF_COMBINATIONS = eINSTANCE.getFeatureEvaluation_PartOfCombinations();

		/**
		 * The meta object literal for the '<em><b>Purpose</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FEATURE_EVALUATION__PURPOSE = eINSTANCE.getFeatureEvaluation_Purpose();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.impl.FindingImpl <em>Finding</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.impl.FindingImpl
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getFinding()
		 * @generated
		 */
		EClass FINDING = eINSTANCE.getFinding();

		/**
		 * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FINDING__ID = eINSTANCE.getFinding_Id();

		/**
		 * The meta object literal for the '<em><b>Category</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FINDING__CATEGORY = eINSTANCE.getFinding_Category();

		/**
		 * The meta object literal for the '<em><b>Relevance Level</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FINDING__RELEVANCE_LEVEL = eINSTANCE.getFinding_RelevanceLevel();

		/**
		 * The meta object literal for the '<em><b>Confidence</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FINDING__CONFIDENCE = eINSTANCE.getFinding_Confidence();

		/**
		 * The meta object literal for the '<em><b>Detected By</b></em>' attribute list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FINDING__DETECTED_BY = eINSTANCE.getFinding_DetectedBy();

		/**
		 * The meta object literal for the '<em><b>Signal Values</b></em>' attribute list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FINDING__SIGNAL_VALUES = eINSTANCE.getFinding_SignalValues();

		/**
		 * The meta object literal for the '<em><b>Rationale</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FINDING__RATIONALE = eINSTANCE.getFinding_Rationale();

		/**
		 * The meta object literal for the '<em><b>Recommendation</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FINDING__RECOMMENDATION = eINSTANCE.getFinding_Recommendation();

		/**
		 * The meta object literal for the '<em><b>Evidence</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference FINDING__EVIDENCE = eINSTANCE.getFinding_Evidence();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.impl.CombinationFindingImpl <em>Combination Finding</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.impl.CombinationFindingImpl
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getCombinationFinding()
		 * @generated
		 */
		EClass COMBINATION_FINDING = eINSTANCE.getCombinationFinding();

		/**
		 * The meta object literal for the '<em><b>Combination Kind</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute COMBINATION_FINDING__COMBINATION_KIND = eINSTANCE.getCombinationFinding_CombinationKind();

		/**
		 * The meta object literal for the '<em><b>Features</b></em>' reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference COMBINATION_FINDING__FEATURES = eINSTANCE.getCombinationFinding_Features();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.impl.EvidenceImpl <em>Evidence</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.impl.EvidenceImpl
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getEvidence()
		 * @generated
		 */
		EClass EVIDENCE = eINSTANCE.getEvidence();

		/**
		 * The meta object literal for the '<em><b>Citation Id</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute EVIDENCE__CITATION_ID = eINSTANCE.getEvidence_CitationId();

		/**
		 * The meta object literal for the '<em><b>Quote</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute EVIDENCE__QUOTE = eINSTANCE.getEvidence_Quote();

		/**
		 * The meta object literal for the '<em><b>Verbatim</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute EVIDENCE__VERBATIM = eINSTANCE.getEvidence_Verbatim();

		/**
		 * The meta object literal for the '<em><b>Relevance</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute EVIDENCE__RELEVANCE = eINSTANCE.getEvidence_Relevance();

		/**
		 * The meta object literal for the '<em><b>Source Ref</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute EVIDENCE__SOURCE_REF = eINSTANCE.getEvidence_SourceRef();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.impl.GdprRequestStatusImpl <em>Gdpr Request Status</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.impl.GdprRequestStatusImpl
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getGdprRequestStatus()
		 * @generated
		 */
		EClass GDPR_REQUEST_STATUS = eINSTANCE.getGdprRequestStatus();

		/**
		 * The meta object literal for the '<em><b>Model Fingerprint</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REQUEST_STATUS__MODEL_FINGERPRINT = eINSTANCE.getGdprRequestStatus_ModelFingerprint();

		/**
		 * The meta object literal for the '<em><b>Ns URI</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REQUEST_STATUS__NS_URI = eINSTANCE.getGdprRequestStatus_NsURI();

		/**
		 * The meta object literal for the '<em><b>Batch Id</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REQUEST_STATUS__BATCH_ID = eINSTANCE.getGdprRequestStatus_BatchId();

		/**
		 * The meta object literal for the '<em><b>Custom Id</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REQUEST_STATUS__CUSTOM_ID = eINSTANCE.getGdprRequestStatus_CustomId();

		/**
		 * The meta object literal for the '<em><b>Report Id</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REQUEST_STATUS__REPORT_ID = eINSTANCE.getGdprRequestStatus_ReportId();

		/**
		 * The meta object literal for the '<em><b>Status</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REQUEST_STATUS__STATUS = eINSTANCE.getGdprRequestStatus_Status();

		/**
		 * The meta object literal for the '<em><b>Submitted At</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REQUEST_STATUS__SUBMITTED_AT = eINSTANCE.getGdprRequestStatus_SubmittedAt();

		/**
		 * The meta object literal for the '<em><b>Ended At</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REQUEST_STATUS__ENDED_AT = eINSTANCE.getGdprRequestStatus_EndedAt();

		/**
		 * The meta object literal for the '<em><b>Message</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REQUEST_STATUS__MESSAGE = eINSTANCE.getGdprRequestStatus_Message();

		/**
		 * The meta object literal for the '<em><b>Continuation Count</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REQUEST_STATUS__CONTINUATION_COUNT = eINSTANCE.getGdprRequestStatus_ContinuationCount();

		/**
		 * The meta object literal for the '<em><b>Output Tokens</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GDPR_REQUEST_STATUS__OUTPUT_TOKENS = eINSTANCE.getGdprRequestStatus_OutputTokens();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.DataCategory <em>Data Category</em>}' enum.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.DataCategory
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getDataCategory()
		 * @generated
		 */
		EEnum DATA_CATEGORY = eINSTANCE.getDataCategory();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.RelevanceLevelType <em>Relevance Level Type</em>}' enum.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.RelevanceLevelType
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getRelevanceLevelType()
		 * @generated
		 */
		EEnum RELEVANCE_LEVEL_TYPE = eINSTANCE.getRelevanceLevelType();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.ConfidenceType <em>Confidence Type</em>}' enum.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.ConfidenceType
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getConfidenceType()
		 * @generated
		 */
		EEnum CONFIDENCE_TYPE = eINSTANCE.getConfidenceType();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.DetectionSignal <em>Detection Signal</em>}' enum.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.DetectionSignal
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getDetectionSignal()
		 * @generated
		 */
		EEnum DETECTION_SIGNAL = eINSTANCE.getDetectionSignal();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.CombinationKind <em>Combination Kind</em>}' enum.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.CombinationKind
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getCombinationKind()
		 * @generated
		 */
		EEnum COMBINATION_KIND = eINSTANCE.getCombinationKind();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.RequestStatusType <em>Request Status Type</em>}' enum.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.RequestStatusType
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getRequestStatusType()
		 * @generated
		 */
		EEnum REQUEST_STATUS_TYPE = eINSTANCE.getRequestStatusType();

		/**
		 * The meta object literal for the '{@link org.eclipse.fennec.model.gdprReport.GdprReportOrigin <em>Gdpr Report Origin</em>}' enum.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.fennec.model.gdprReport.GdprReportOrigin
		 * @see org.eclipse.fennec.model.gdprReport.impl.GDPRReportPackageImpl#getGdprReportOrigin()
		 * @generated
		 */
		EEnum GDPR_REPORT_ORIGIN = eINSTANCE.getGdprReportOrigin();

	}

} //GDPRReportPackage
