/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 * 
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Data In Motion Consulting - initial implementation
 */
package org.eclipse.fennec.model.gdprReport;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.osgi.annotation.versioning.ProviderType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gdpr Report</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * Root of a GDPR review of one Ecore metamodel. Exactly one instance per review run. It records what was reviewed (subject), which revision of the legal text the evidence was quoted from (corpus), one ClassifierEvaluation per examined classifier, and any cross-classifier combination findings.
 * <!-- end-model-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.GdprReport#getReportId <em>Report Id</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.GdprReport#getName <em>Name</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.GdprReport#getGeneratedAt <em>Generated At</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.GdprReport#getGeneratedBy <em>Generated By</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.GdprReport#getSubject <em>Subject</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.GdprReport#getCorpus <em>Corpus</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.GdprReport#getClassifierEvaluation <em>Classifier Evaluation</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.GdprReport#getCombinations <em>Combinations</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.GdprReport#getDisclaimer <em>Disclaimer</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.GdprReport#getOrigin <em>Origin</em>}</li>
 * </ul>
 *
 * @see org.eclipse.fennec.model.gdprReport.GDPRReportPackage#getGdprReport()
 * @model
 * @generated
 */
@ProviderType
public interface GdprReport extends EObject {
	/**
	 * Returns the value of the '<em><b>Report Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * The unique identifier for this report
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Report Id</em>' attribute.
	 * @see #setReportId(String)
	 * @see org.eclipse.fennec.model.gdprReport.GDPRReportPackage#getGdprReport_ReportId()
	 * @model
	 * @generated
	 */
	String getReportId();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getReportId <em>Report Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Report Id</em>' attribute.
	 * @see #getReportId()
	 * @generated
	 */
	void setReportId(String value);

	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Human readable title of the review, e.g. 'GDPR review of clinic 1.0.0'.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.eclipse.fennec.model.gdprReport.GDPRReportPackage#getGdprReport_Name()
	 * @model
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Generated At</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * When the review ran, as an ISO-8601 UTC instant, e.g. 2026-09-09T14:20:00Z.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Generated At</em>' attribute.
	 * @see #setGeneratedAt(String)
	 * @see org.eclipse.fennec.model.gdprReport.GDPRReportPackage#getGdprReport_GeneratedAt()
	 * @model
	 * @generated
	 */
	String getGeneratedAt();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getGeneratedAt <em>Generated At</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Generated At</em>' attribute.
	 * @see #getGeneratedAt()
	 * @generated
	 */
	void setGeneratedAt(String value);

	/**
	 * Returns the value of the '<em><b>Generated By</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * The language model that produced this review, as the provider names it, e.g. claude-sonnet-4-6. Two models reviewing the same metamodel do not agree in every particular - measured on one 3.4KB model, two models agreed exactly on the classifiers carrying obvious personal data and differed on the ones turning on a processing purpose - so a finding cannot be weighed without knowing what produced it.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Generated By</em>' attribute.
	 * @see #setGeneratedBy(String)
	 * @see org.eclipse.fennec.model.gdprReport.GDPRReportPackage#getGdprReport_GeneratedBy()
	 * @model
	 * @generated
	 */
	String getGeneratedBy();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getGeneratedBy <em>Generated By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Generated By</em>' attribute.
	 * @see #getGeneratedBy()
	 * @generated
	 */
	void setGeneratedBy(String value);

	/**
	 * Returns the value of the '<em><b>Subject</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Required. The metamodel that was reviewed, including the fingerprint that pins the exact revision.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Subject</em>' containment reference.
	 * @see #setSubject(SubjectModel)
	 * @see org.eclipse.fennec.model.gdprReport.GDPRReportPackage#getGdprReport_Subject()
	 * @model containment="true" required="true"
	 * @generated
	 */
	SubjectModel getSubject();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getSubject <em>Subject</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Subject</em>' containment reference.
	 * @see #getSubject()
	 * @generated
	 */
	void setSubject(SubjectModel value);

	/**
	 * Returns the value of the '<em><b>Corpus</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Required. Which revision of the legal text the quotes came from. Without it a quote cannot be verified later.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Corpus</em>' containment reference.
	 * @see #setCorpus(LegalCorpusRef)
	 * @see org.eclipse.fennec.model.gdprReport.GDPRReportPackage#getGdprReport_Corpus()
	 * @model containment="true" required="true"
	 * @generated
	 */
	LegalCorpusRef getCorpus();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getCorpus <em>Corpus</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Corpus</em>' containment reference.
	 * @see #getCorpus()
	 * @generated
	 */
	void setCorpus(LegalCorpusRef value);

	/**
	 * Returns the value of the '<em><b>Classifier Evaluation</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.fennec.model.gdprReport.ClassifierEvaluation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * One entry per classifier that was examined. Add an entry even when nothing was found, so a reader can distinguish 'examined and clean' from 'never examined'.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Classifier Evaluation</em>' containment reference list.
	 * @see org.eclipse.fennec.model.gdprReport.GDPRReportPackage#getGdprReport_ClassifierEvaluation()
	 * @model containment="true"
	 * @generated
	 */
	EList<ClassifierEvaluation> getClassifierEvaluation();

	/**
	 * Returns the value of the '<em><b>Combinations</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.fennec.model.gdprReport.CombinationFinding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Findings that arise from two or more features together. They are held here, not under a ClassifierEvaluation, because a combination may span several classifiers and would otherwise need an arbitrary owner.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Combinations</em>' containment reference list.
	 * @see org.eclipse.fennec.model.gdprReport.GDPRReportPackage#getGdprReport_Combinations()
	 * @model containment="true"
	 * @generated
	 */
	EList<CombinationFinding> getCombinations();

	/**
	 * Returns the value of the '<em><b>Disclaimer</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Statement of what the report is and is not. It is decision support for a data protection officer: it flags features needing human review and must not assert compliance or non-compliance.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Disclaimer</em>' attribute.
	 * @see #setDisclaimer(String)
	 * @see org.eclipse.fennec.model.gdprReport.GDPRReportPackage#getGdprReport_Disclaimer()
	 * @model
	 * @generated
	 */
	String getDisclaimer();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getDisclaimer <em>Disclaimer</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Disclaimer</em>' attribute.
	 * @see #getDisclaimer()
	 * @generated
	 */
	void setDisclaimer(String value);

	/**
	 * Returns the value of the '<em><b>Origin</b></em>' attribute.
	 * The literals are from the enumeration {@link org.eclipse.fennec.model.gdprReport.GdprReportOrigin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * The origin of the report, namely whether it was redacted by an AI agent or by a human
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Origin</em>' attribute.
	 * @see org.eclipse.fennec.model.gdprReport.GdprReportOrigin
	 * @see #setOrigin(GdprReportOrigin)
	 * @see org.eclipse.fennec.model.gdprReport.GDPRReportPackage#getGdprReport_Origin()
	 * @model
	 * @generated
	 */
	GdprReportOrigin getOrigin();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReport.GdprReport#getOrigin <em>Origin</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Origin</em>' attribute.
	 * @see org.eclipse.fennec.model.gdprReport.GdprReportOrigin
	 * @see #getOrigin()
	 * @generated
	 */
	void setOrigin(GdprReportOrigin value);

} // GdprReport
