/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 * 
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Data In Motion Consulting - initial implementation
 */
package org.eclipse.fennec.model.compliance.history.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeUniqueEList;

import org.eclipse.fennec.model.compliance.history.HistoryPackage;
import org.eclipse.fennec.model.compliance.history.ReportRevision;
import org.eclipse.fennec.model.compliance.history.RevisionOrigin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Report Revision</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.fennec.model.compliance.history.impl.ReportRevisionImpl#getRevisionNumber <em>Revision Number</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.history.impl.ReportRevisionImpl#getReportId <em>Report Id</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.history.impl.ReportRevisionImpl#getSubjectFingerprint <em>Subject Fingerprint</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.history.impl.ReportRevisionImpl#getGeneratedAt <em>Generated At</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.history.impl.ReportRevisionImpl#getGeneratedBy <em>Generated By</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.history.impl.ReportRevisionImpl#getOrigin <em>Origin</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.history.impl.ReportRevisionImpl#getFindingCount <em>Finding Count</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.history.impl.ReportRevisionImpl#getChangeCount <em>Change Count</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.history.impl.ReportRevisionImpl#getContextVersions <em>Context Versions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReportRevisionImpl extends MinimalEObjectImpl.Container implements ReportRevision {
	/**
	 * The default value of the '{@link #getRevisionNumber() <em>Revision Number</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRevisionNumber()
	 * @generated
	 * @ordered
	 */
	protected static final int REVISION_NUMBER_EDEFAULT = 0;

	/**
	 * The cached value of the '{@link #getRevisionNumber() <em>Revision Number</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRevisionNumber()
	 * @generated
	 * @ordered
	 */
	protected int revisionNumber = REVISION_NUMBER_EDEFAULT;

	/**
	 * The default value of the '{@link #getReportId() <em>Report Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getReportId()
	 * @generated
	 * @ordered
	 */
	protected static final String REPORT_ID_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getReportId() <em>Report Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getReportId()
	 * @generated
	 * @ordered
	 */
	protected String reportId = REPORT_ID_EDEFAULT;

	/**
	 * The default value of the '{@link #getSubjectFingerprint() <em>Subject Fingerprint</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getSubjectFingerprint()
	 * @generated
	 * @ordered
	 */
	protected static final String SUBJECT_FINGERPRINT_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getSubjectFingerprint() <em>Subject Fingerprint</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getSubjectFingerprint()
	 * @generated
	 * @ordered
	 */
	protected String subjectFingerprint = SUBJECT_FINGERPRINT_EDEFAULT;

	/**
	 * The default value of the '{@link #getGeneratedAt() <em>Generated At</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedAt()
	 * @generated
	 * @ordered
	 */
	protected static final String GENERATED_AT_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getGeneratedAt() <em>Generated At</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedAt()
	 * @generated
	 * @ordered
	 */
	protected String generatedAt = GENERATED_AT_EDEFAULT;

	/**
	 * The default value of the '{@link #getGeneratedBy() <em>Generated By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected static final String GENERATED_BY_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getGeneratedBy() <em>Generated By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected String generatedBy = GENERATED_BY_EDEFAULT;

	/**
	 * The default value of the '{@link #getOrigin() <em>Origin</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOrigin()
	 * @generated
	 * @ordered
	 */
	protected static final RevisionOrigin ORIGIN_EDEFAULT = RevisionOrigin.UNKNOWN;

	/**
	 * The cached value of the '{@link #getOrigin() <em>Origin</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOrigin()
	 * @generated
	 * @ordered
	 */
	protected RevisionOrigin origin = ORIGIN_EDEFAULT;

	/**
	 * The default value of the '{@link #getFindingCount() <em>Finding Count</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getFindingCount()
	 * @generated
	 * @ordered
	 */
	protected static final int FINDING_COUNT_EDEFAULT = 0;

	/**
	 * The cached value of the '{@link #getFindingCount() <em>Finding Count</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getFindingCount()
	 * @generated
	 * @ordered
	 */
	protected int findingCount = FINDING_COUNT_EDEFAULT;

	/**
	 * The default value of the '{@link #getChangeCount() <em>Change Count</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getChangeCount()
	 * @generated
	 * @ordered
	 */
	protected static final int CHANGE_COUNT_EDEFAULT = 0;

	/**
	 * The cached value of the '{@link #getChangeCount() <em>Change Count</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getChangeCount()
	 * @generated
	 * @ordered
	 */
	protected int changeCount = CHANGE_COUNT_EDEFAULT;

	/**
	 * The cached value of the '{@link #getContextVersions() <em>Context Versions</em>}' attribute list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getContextVersions()
	 * @generated
	 * @ordered
	 */
	protected EList<String> contextVersions;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReportRevisionImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return HistoryPackage.Literals.REPORT_REVISION;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public int getRevisionNumber() {
		return revisionNumber;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setRevisionNumber(int newRevisionNumber) {
		int oldRevisionNumber = revisionNumber;
		revisionNumber = newRevisionNumber;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, HistoryPackage.REPORT_REVISION__REVISION_NUMBER, oldRevisionNumber, revisionNumber));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getReportId() {
		return reportId;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setReportId(String newReportId) {
		String oldReportId = reportId;
		reportId = newReportId;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, HistoryPackage.REPORT_REVISION__REPORT_ID, oldReportId, reportId));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getSubjectFingerprint() {
		return subjectFingerprint;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setSubjectFingerprint(String newSubjectFingerprint) {
		String oldSubjectFingerprint = subjectFingerprint;
		subjectFingerprint = newSubjectFingerprint;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, HistoryPackage.REPORT_REVISION__SUBJECT_FINGERPRINT, oldSubjectFingerprint, subjectFingerprint));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getGeneratedAt() {
		return generatedAt;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setGeneratedAt(String newGeneratedAt) {
		String oldGeneratedAt = generatedAt;
		generatedAt = newGeneratedAt;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, HistoryPackage.REPORT_REVISION__GENERATED_AT, oldGeneratedAt, generatedAt));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getGeneratedBy() {
		return generatedBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setGeneratedBy(String newGeneratedBy) {
		String oldGeneratedBy = generatedBy;
		generatedBy = newGeneratedBy;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, HistoryPackage.REPORT_REVISION__GENERATED_BY, oldGeneratedBy, generatedBy));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public RevisionOrigin getOrigin() {
		return origin;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setOrigin(RevisionOrigin newOrigin) {
		RevisionOrigin oldOrigin = origin;
		origin = newOrigin == null ? ORIGIN_EDEFAULT : newOrigin;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, HistoryPackage.REPORT_REVISION__ORIGIN, oldOrigin, origin));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public int getFindingCount() {
		return findingCount;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setFindingCount(int newFindingCount) {
		int oldFindingCount = findingCount;
		findingCount = newFindingCount;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, HistoryPackage.REPORT_REVISION__FINDING_COUNT, oldFindingCount, findingCount));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public int getChangeCount() {
		return changeCount;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setChangeCount(int newChangeCount) {
		int oldChangeCount = changeCount;
		changeCount = newChangeCount;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, HistoryPackage.REPORT_REVISION__CHANGE_COUNT, oldChangeCount, changeCount));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<String> getContextVersions() {
		if (contextVersions == null) {
			contextVersions = new EDataTypeUniqueEList<String>(String.class, this, HistoryPackage.REPORT_REVISION__CONTEXT_VERSIONS);
		}
		return contextVersions;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case HistoryPackage.REPORT_REVISION__REVISION_NUMBER:
				return getRevisionNumber();
			case HistoryPackage.REPORT_REVISION__REPORT_ID:
				return getReportId();
			case HistoryPackage.REPORT_REVISION__SUBJECT_FINGERPRINT:
				return getSubjectFingerprint();
			case HistoryPackage.REPORT_REVISION__GENERATED_AT:
				return getGeneratedAt();
			case HistoryPackage.REPORT_REVISION__GENERATED_BY:
				return getGeneratedBy();
			case HistoryPackage.REPORT_REVISION__ORIGIN:
				return getOrigin();
			case HistoryPackage.REPORT_REVISION__FINDING_COUNT:
				return getFindingCount();
			case HistoryPackage.REPORT_REVISION__CHANGE_COUNT:
				return getChangeCount();
			case HistoryPackage.REPORT_REVISION__CONTEXT_VERSIONS:
				return getContextVersions();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case HistoryPackage.REPORT_REVISION__REVISION_NUMBER:
				setRevisionNumber((Integer)newValue);
				return;
			case HistoryPackage.REPORT_REVISION__REPORT_ID:
				setReportId((String)newValue);
				return;
			case HistoryPackage.REPORT_REVISION__SUBJECT_FINGERPRINT:
				setSubjectFingerprint((String)newValue);
				return;
			case HistoryPackage.REPORT_REVISION__GENERATED_AT:
				setGeneratedAt((String)newValue);
				return;
			case HistoryPackage.REPORT_REVISION__GENERATED_BY:
				setGeneratedBy((String)newValue);
				return;
			case HistoryPackage.REPORT_REVISION__ORIGIN:
				setOrigin((RevisionOrigin)newValue);
				return;
			case HistoryPackage.REPORT_REVISION__FINDING_COUNT:
				setFindingCount((Integer)newValue);
				return;
			case HistoryPackage.REPORT_REVISION__CHANGE_COUNT:
				setChangeCount((Integer)newValue);
				return;
			case HistoryPackage.REPORT_REVISION__CONTEXT_VERSIONS:
				getContextVersions().clear();
				getContextVersions().addAll((Collection<? extends String>)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case HistoryPackage.REPORT_REVISION__REVISION_NUMBER:
				setRevisionNumber(REVISION_NUMBER_EDEFAULT);
				return;
			case HistoryPackage.REPORT_REVISION__REPORT_ID:
				setReportId(REPORT_ID_EDEFAULT);
				return;
			case HistoryPackage.REPORT_REVISION__SUBJECT_FINGERPRINT:
				setSubjectFingerprint(SUBJECT_FINGERPRINT_EDEFAULT);
				return;
			case HistoryPackage.REPORT_REVISION__GENERATED_AT:
				setGeneratedAt(GENERATED_AT_EDEFAULT);
				return;
			case HistoryPackage.REPORT_REVISION__GENERATED_BY:
				setGeneratedBy(GENERATED_BY_EDEFAULT);
				return;
			case HistoryPackage.REPORT_REVISION__ORIGIN:
				setOrigin(ORIGIN_EDEFAULT);
				return;
			case HistoryPackage.REPORT_REVISION__FINDING_COUNT:
				setFindingCount(FINDING_COUNT_EDEFAULT);
				return;
			case HistoryPackage.REPORT_REVISION__CHANGE_COUNT:
				setChangeCount(CHANGE_COUNT_EDEFAULT);
				return;
			case HistoryPackage.REPORT_REVISION__CONTEXT_VERSIONS:
				getContextVersions().clear();
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case HistoryPackage.REPORT_REVISION__REVISION_NUMBER:
				return revisionNumber != REVISION_NUMBER_EDEFAULT;
			case HistoryPackage.REPORT_REVISION__REPORT_ID:
				return REPORT_ID_EDEFAULT == null ? reportId != null : !REPORT_ID_EDEFAULT.equals(reportId);
			case HistoryPackage.REPORT_REVISION__SUBJECT_FINGERPRINT:
				return SUBJECT_FINGERPRINT_EDEFAULT == null ? subjectFingerprint != null : !SUBJECT_FINGERPRINT_EDEFAULT.equals(subjectFingerprint);
			case HistoryPackage.REPORT_REVISION__GENERATED_AT:
				return GENERATED_AT_EDEFAULT == null ? generatedAt != null : !GENERATED_AT_EDEFAULT.equals(generatedAt);
			case HistoryPackage.REPORT_REVISION__GENERATED_BY:
				return GENERATED_BY_EDEFAULT == null ? generatedBy != null : !GENERATED_BY_EDEFAULT.equals(generatedBy);
			case HistoryPackage.REPORT_REVISION__ORIGIN:
				return origin != ORIGIN_EDEFAULT;
			case HistoryPackage.REPORT_REVISION__FINDING_COUNT:
				return findingCount != FINDING_COUNT_EDEFAULT;
			case HistoryPackage.REPORT_REVISION__CHANGE_COUNT:
				return changeCount != CHANGE_COUNT_EDEFAULT;
			case HistoryPackage.REPORT_REVISION__CONTEXT_VERSIONS:
				return contextVersions != null && !contextVersions.isEmpty();
		}
		return super.eIsSet(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String toString() {
		if (eIsProxy()) return super.toString();

		StringBuilder result = new StringBuilder(super.toString());
		result.append(" (revisionNumber: ");
		result.append(revisionNumber);
		result.append(", reportId: ");
		result.append(reportId);
		result.append(", subjectFingerprint: ");
		result.append(subjectFingerprint);
		result.append(", generatedAt: ");
		result.append(generatedAt);
		result.append(", generatedBy: ");
		result.append(generatedBy);
		result.append(", origin: ");
		result.append(origin);
		result.append(", findingCount: ");
		result.append(findingCount);
		result.append(", changeCount: ");
		result.append(changeCount);
		result.append(", contextVersions: ");
		result.append(contextVersions);
		result.append(')');
		return result.toString();
	}

} //ReportRevisionImpl
