/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 * 
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Data In Motion Consulting - initial implementation
 */
package org.eclipse.fennec.model.compliance.report.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.eclipse.fennec.model.compliance.context.ContextRef;

import org.eclipse.fennec.model.compliance.report.CombinationFinding;
import org.eclipse.fennec.model.compliance.report.ComplianceReport;
import org.eclipse.fennec.model.compliance.report.Evaluation;
import org.eclipse.fennec.model.compliance.report.ReportOrigin;
import org.eclipse.fennec.model.compliance.report.ReportPackage;
import org.eclipse.fennec.model.compliance.report.Subject;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Compliance Report</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.impl.ComplianceReportImpl#getReportId <em>Report Id</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.impl.ComplianceReportImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.impl.ComplianceReportImpl#getGeneratedAt <em>Generated At</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.impl.ComplianceReportImpl#getGeneratedBy <em>Generated By</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.impl.ComplianceReportImpl#getSubject <em>Subject</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.impl.ComplianceReportImpl#getEvaluations <em>Evaluations</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.impl.ComplianceReportImpl#getCombinations <em>Combinations</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.impl.ComplianceReportImpl#getDisclaimer <em>Disclaimer</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.impl.ComplianceReportImpl#getOrigin <em>Origin</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.impl.ComplianceReportImpl#getContexts <em>Contexts</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComplianceReportImpl extends MinimalEObjectImpl.Container implements ComplianceReport {
	/**
	 * The default value of the '{@link #getReportId() <em>Report Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getReportId()
	 * @generated
	 * @ordered
	 */
	protected static final String REPORT_ID_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getReportId() <em>Report Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getReportId()
	 * @generated
	 * @ordered
	 */
	protected String reportId = REPORT_ID_EDEFAULT;

	/**
	 * The default value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
	protected static final String NAME_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
	protected String name = NAME_EDEFAULT;

	/**
	 * The default value of the '{@link #getGeneratedAt() <em>Generated At</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedAt()
	 * @generated
	 * @ordered
	 */
	protected static final String GENERATED_AT_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getGeneratedAt() <em>Generated At</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedAt()
	 * @generated
	 * @ordered
	 */
	protected String generatedAt = GENERATED_AT_EDEFAULT;

	/**
	 * The default value of the '{@link #getGeneratedBy() <em>Generated By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected static final String GENERATED_BY_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getGeneratedBy() <em>Generated By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected String generatedBy = GENERATED_BY_EDEFAULT;

	/**
	 * The cached value of the '{@link #getSubject() <em>Subject</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getSubject()
	 * @generated
	 * @ordered
	 */
	protected Subject subject;

	/**
	 * The cached value of the '{@link #getEvaluations() <em>Evaluations</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getEvaluations()
	 * @generated
	 * @ordered
	 */
	protected EList<Evaluation> evaluations;

	/**
	 * The cached value of the '{@link #getCombinations() <em>Combinations</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getCombinations()
	 * @generated
	 * @ordered
	 */
	protected EList<CombinationFinding> combinations;

	/**
	 * The default value of the '{@link #getDisclaimer() <em>Disclaimer</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDisclaimer()
	 * @generated
	 * @ordered
	 */
	protected static final String DISCLAIMER_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getDisclaimer() <em>Disclaimer</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDisclaimer()
	 * @generated
	 * @ordered
	 */
	protected String disclaimer = DISCLAIMER_EDEFAULT;

	/**
	 * The default value of the '{@link #getOrigin() <em>Origin</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOrigin()
	 * @generated
	 * @ordered
	 */
	protected static final ReportOrigin ORIGIN_EDEFAULT = ReportOrigin.UNKNOWN;

	/**
	 * The cached value of the '{@link #getOrigin() <em>Origin</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOrigin()
	 * @generated
	 * @ordered
	 */
	protected ReportOrigin origin = ORIGIN_EDEFAULT;

	/**
	 * The cached value of the '{@link #getContexts() <em>Contexts</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getContexts()
	 * @generated
	 * @ordered
	 */
	protected EList<ContextRef> contexts;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComplianceReportImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return ReportPackage.Literals.COMPLIANCE_REPORT;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getReportId() {
		return reportId;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setReportId(String newReportId) {
		String oldReportId = reportId;
		reportId = newReportId;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ReportPackage.COMPLIANCE_REPORT__REPORT_ID, oldReportId, reportId));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getName() {
		return name;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setName(String newName) {
		String oldName = name;
		name = newName;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ReportPackage.COMPLIANCE_REPORT__NAME, oldName, name));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getGeneratedAt() {
		return generatedAt;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setGeneratedAt(String newGeneratedAt) {
		String oldGeneratedAt = generatedAt;
		generatedAt = newGeneratedAt;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ReportPackage.COMPLIANCE_REPORT__GENERATED_AT, oldGeneratedAt, generatedAt));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getGeneratedBy() {
		return generatedBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setGeneratedBy(String newGeneratedBy) {
		String oldGeneratedBy = generatedBy;
		generatedBy = newGeneratedBy;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ReportPackage.COMPLIANCE_REPORT__GENERATED_BY, oldGeneratedBy, generatedBy));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Subject getSubject() {
		return subject;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetSubject(Subject newSubject, NotificationChain msgs) {
		Subject oldSubject = subject;
		subject = newSubject;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ReportPackage.COMPLIANCE_REPORT__SUBJECT, oldSubject, newSubject);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setSubject(Subject newSubject) {
		if (newSubject != subject) {
			NotificationChain msgs = null;
			if (subject != null)
				msgs = ((InternalEObject)subject).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ReportPackage.COMPLIANCE_REPORT__SUBJECT, null, msgs);
			if (newSubject != null)
				msgs = ((InternalEObject)newSubject).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ReportPackage.COMPLIANCE_REPORT__SUBJECT, null, msgs);
			msgs = basicSetSubject(newSubject, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ReportPackage.COMPLIANCE_REPORT__SUBJECT, newSubject, newSubject));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<Evaluation> getEvaluations() {
		if (evaluations == null) {
			evaluations = new EObjectContainmentEList<Evaluation>(Evaluation.class, this, ReportPackage.COMPLIANCE_REPORT__EVALUATIONS);
		}
		return evaluations;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<CombinationFinding> getCombinations() {
		if (combinations == null) {
			combinations = new EObjectContainmentEList<CombinationFinding>(CombinationFinding.class, this, ReportPackage.COMPLIANCE_REPORT__COMBINATIONS);
		}
		return combinations;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getDisclaimer() {
		return disclaimer;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setDisclaimer(String newDisclaimer) {
		String oldDisclaimer = disclaimer;
		disclaimer = newDisclaimer;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ReportPackage.COMPLIANCE_REPORT__DISCLAIMER, oldDisclaimer, disclaimer));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ReportOrigin getOrigin() {
		return origin;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setOrigin(ReportOrigin newOrigin) {
		ReportOrigin oldOrigin = origin;
		origin = newOrigin == null ? ORIGIN_EDEFAULT : newOrigin;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ReportPackage.COMPLIANCE_REPORT__ORIGIN, oldOrigin, origin));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<ContextRef> getContexts() {
		if (contexts == null) {
			contexts = new EObjectContainmentEList<ContextRef>(ContextRef.class, this, ReportPackage.COMPLIANCE_REPORT__CONTEXTS);
		}
		return contexts;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case ReportPackage.COMPLIANCE_REPORT__SUBJECT:
				return basicSetSubject(null, msgs);
			case ReportPackage.COMPLIANCE_REPORT__EVALUATIONS:
				return ((InternalEList<?>)getEvaluations()).basicRemove(otherEnd, msgs);
			case ReportPackage.COMPLIANCE_REPORT__COMBINATIONS:
				return ((InternalEList<?>)getCombinations()).basicRemove(otherEnd, msgs);
			case ReportPackage.COMPLIANCE_REPORT__CONTEXTS:
				return ((InternalEList<?>)getContexts()).basicRemove(otherEnd, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case ReportPackage.COMPLIANCE_REPORT__REPORT_ID:
				return getReportId();
			case ReportPackage.COMPLIANCE_REPORT__NAME:
				return getName();
			case ReportPackage.COMPLIANCE_REPORT__GENERATED_AT:
				return getGeneratedAt();
			case ReportPackage.COMPLIANCE_REPORT__GENERATED_BY:
				return getGeneratedBy();
			case ReportPackage.COMPLIANCE_REPORT__SUBJECT:
				return getSubject();
			case ReportPackage.COMPLIANCE_REPORT__EVALUATIONS:
				return getEvaluations();
			case ReportPackage.COMPLIANCE_REPORT__COMBINATIONS:
				return getCombinations();
			case ReportPackage.COMPLIANCE_REPORT__DISCLAIMER:
				return getDisclaimer();
			case ReportPackage.COMPLIANCE_REPORT__ORIGIN:
				return getOrigin();
			case ReportPackage.COMPLIANCE_REPORT__CONTEXTS:
				return getContexts();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case ReportPackage.COMPLIANCE_REPORT__REPORT_ID:
				setReportId((String)newValue);
				return;
			case ReportPackage.COMPLIANCE_REPORT__NAME:
				setName((String)newValue);
				return;
			case ReportPackage.COMPLIANCE_REPORT__GENERATED_AT:
				setGeneratedAt((String)newValue);
				return;
			case ReportPackage.COMPLIANCE_REPORT__GENERATED_BY:
				setGeneratedBy((String)newValue);
				return;
			case ReportPackage.COMPLIANCE_REPORT__SUBJECT:
				setSubject((Subject)newValue);
				return;
			case ReportPackage.COMPLIANCE_REPORT__EVALUATIONS:
				getEvaluations().clear();
				getEvaluations().addAll((Collection<? extends Evaluation>)newValue);
				return;
			case ReportPackage.COMPLIANCE_REPORT__COMBINATIONS:
				getCombinations().clear();
				getCombinations().addAll((Collection<? extends CombinationFinding>)newValue);
				return;
			case ReportPackage.COMPLIANCE_REPORT__DISCLAIMER:
				setDisclaimer((String)newValue);
				return;
			case ReportPackage.COMPLIANCE_REPORT__ORIGIN:
				setOrigin((ReportOrigin)newValue);
				return;
			case ReportPackage.COMPLIANCE_REPORT__CONTEXTS:
				getContexts().clear();
				getContexts().addAll((Collection<? extends ContextRef>)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case ReportPackage.COMPLIANCE_REPORT__REPORT_ID:
				setReportId(REPORT_ID_EDEFAULT);
				return;
			case ReportPackage.COMPLIANCE_REPORT__NAME:
				setName(NAME_EDEFAULT);
				return;
			case ReportPackage.COMPLIANCE_REPORT__GENERATED_AT:
				setGeneratedAt(GENERATED_AT_EDEFAULT);
				return;
			case ReportPackage.COMPLIANCE_REPORT__GENERATED_BY:
				setGeneratedBy(GENERATED_BY_EDEFAULT);
				return;
			case ReportPackage.COMPLIANCE_REPORT__SUBJECT:
				setSubject((Subject)null);
				return;
			case ReportPackage.COMPLIANCE_REPORT__EVALUATIONS:
				getEvaluations().clear();
				return;
			case ReportPackage.COMPLIANCE_REPORT__COMBINATIONS:
				getCombinations().clear();
				return;
			case ReportPackage.COMPLIANCE_REPORT__DISCLAIMER:
				setDisclaimer(DISCLAIMER_EDEFAULT);
				return;
			case ReportPackage.COMPLIANCE_REPORT__ORIGIN:
				setOrigin(ORIGIN_EDEFAULT);
				return;
			case ReportPackage.COMPLIANCE_REPORT__CONTEXTS:
				getContexts().clear();
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case ReportPackage.COMPLIANCE_REPORT__REPORT_ID:
				return REPORT_ID_EDEFAULT == null ? reportId != null : !REPORT_ID_EDEFAULT.equals(reportId);
			case ReportPackage.COMPLIANCE_REPORT__NAME:
				return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
			case ReportPackage.COMPLIANCE_REPORT__GENERATED_AT:
				return GENERATED_AT_EDEFAULT == null ? generatedAt != null : !GENERATED_AT_EDEFAULT.equals(generatedAt);
			case ReportPackage.COMPLIANCE_REPORT__GENERATED_BY:
				return GENERATED_BY_EDEFAULT == null ? generatedBy != null : !GENERATED_BY_EDEFAULT.equals(generatedBy);
			case ReportPackage.COMPLIANCE_REPORT__SUBJECT:
				return subject != null;
			case ReportPackage.COMPLIANCE_REPORT__EVALUATIONS:
				return evaluations != null && !evaluations.isEmpty();
			case ReportPackage.COMPLIANCE_REPORT__COMBINATIONS:
				return combinations != null && !combinations.isEmpty();
			case ReportPackage.COMPLIANCE_REPORT__DISCLAIMER:
				return DISCLAIMER_EDEFAULT == null ? disclaimer != null : !DISCLAIMER_EDEFAULT.equals(disclaimer);
			case ReportPackage.COMPLIANCE_REPORT__ORIGIN:
				return origin != ORIGIN_EDEFAULT;
			case ReportPackage.COMPLIANCE_REPORT__CONTEXTS:
				return contexts != null && !contexts.isEmpty();
		}
		return super.eIsSet(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String toString() {
		if (eIsProxy()) return super.toString();

		StringBuilder result = new StringBuilder(super.toString());
		result.append(" (reportId: ");
		result.append(reportId);
		result.append(", name: ");
		result.append(name);
		result.append(", generatedAt: ");
		result.append(generatedAt);
		result.append(", generatedBy: ");
		result.append(generatedBy);
		result.append(", disclaimer: ");
		result.append(disclaimer);
		result.append(", origin: ");
		result.append(origin);
		result.append(')');
		return result.toString();
	}

} //ComplianceReportImpl
