/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 * 
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Data In Motion Consulting - initial implementation
 */
package org.eclipse.fennec.model.compliance.report;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.fennec.model.compliance.context.ContextRef;

import org.osgi.annotation.versioning.ProviderType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Compliance Report</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * The result of one review of one subject against one or more compliance contexts. Each revision of a review is its own report; the history model lines them up.
 * <!-- end-model-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getReportId <em>Report Id</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getName <em>Name</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getGeneratedAt <em>Generated At</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getGeneratedBy <em>Generated By</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getSubject <em>Subject</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getEvaluations <em>Evaluations</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getCombinations <em>Combinations</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getDisclaimer <em>Disclaimer</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getOrigin <em>Origin</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getContexts <em>Contexts</em>}</li>
 * </ul>
 *
 * @see org.eclipse.fennec.model.compliance.report.ReportPackage#getComplianceReport()
 * @model
 * @generated
 */
@ProviderType
public interface ComplianceReport extends EObject {
	/**
	 * Returns the value of the '<em><b>Report Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * The unique identifier for this report
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Report Id</em>' attribute.
	 * @see #setReportId(String)
	 * @see org.eclipse.fennec.model.compliance.report.ReportPackage#getComplianceReport_ReportId()
	 * @model
	 * @generated
	 */
	String getReportId();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getReportId <em>Report Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Report Id</em>' attribute.
	 * @see #getReportId()
	 * @generated
	 */
	void setReportId(String value);

	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Human readable title of the review, e.g. 'GDPR review of clinic 1.0.0'.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.eclipse.fennec.model.compliance.report.ReportPackage#getComplianceReport_Name()
	 * @model
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Generated At</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * When the review ran, as an ISO-8601 UTC instant, e.g. 2026-09-09T14:20:00Z.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Generated At</em>' attribute.
	 * @see #setGeneratedAt(String)
	 * @see org.eclipse.fennec.model.compliance.report.ReportPackage#getComplianceReport_GeneratedAt()
	 * @model
	 * @generated
	 */
	String getGeneratedAt();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getGeneratedAt <em>Generated At</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Generated At</em>' attribute.
	 * @see #getGeneratedAt()
	 * @generated
	 */
	void setGeneratedAt(String value);

	/**
	 * Returns the value of the '<em><b>Generated By</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * The language model that produced this review, as the provider names it, e.g. claude-sonnet-4-6. Two models reviewing the same metamodel do not agree in every particular - measured on one 3.4KB model, two models agreed exactly on the classifiers carrying obvious personal data and differed on the ones turning on a processing purpose - so a finding cannot be weighed without knowing what produced it.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Generated By</em>' attribute.
	 * @see #setGeneratedBy(String)
	 * @see org.eclipse.fennec.model.compliance.report.ReportPackage#getComplianceReport_GeneratedBy()
	 * @model
	 * @generated
	 */
	String getGeneratedBy();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getGeneratedBy <em>Generated By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Generated By</em>' attribute.
	 * @see #getGeneratedBy()
	 * @generated
	 */
	void setGeneratedBy(String value);

	/**
	 * Returns the value of the '<em><b>Subject</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Required. What was reviewed, including the fingerprint that pins the exact revision: a PackageSubject for a metamodel, a TransformationSubject for a compiled transformation. Everything else the review rests on is recorded inside it.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Subject</em>' containment reference.
	 * @see #setSubject(Subject)
	 * @see org.eclipse.fennec.model.compliance.report.ReportPackage#getComplianceReport_Subject()
	 * @model containment="true" required="true"
	 * @generated
	 */
	Subject getSubject();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getSubject <em>Subject</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Subject</em>' containment reference.
	 * @see #getSubject()
	 * @generated
	 */
	void setSubject(Subject value);

	/**
	 * Returns the value of the '<em><b>Evaluations</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.fennec.model.compliance.report.Evaluation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * One entry per thing that was examined: a ClassifierEvaluation per classifier in a metamodel review, a FlowEvaluation per source-to-target path in a transformation review. Add an entry even when nothing was found, so a reader can distinguish 'examined and clean' from 'never examined'.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Evaluations</em>' containment reference list.
	 * @see org.eclipse.fennec.model.compliance.report.ReportPackage#getComplianceReport_Evaluations()
	 * @model containment="true"
	 * @generated
	 */
	EList<Evaluation> getEvaluations();

	/**
	 * Returns the value of the '<em><b>Combinations</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.fennec.model.compliance.report.CombinationFinding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Findings that arise from two or more evaluations together: several features that identify a person only in combination, or several flows meeting in one target field. They are held here, not under the evaluations themselves, because a combination may span several classifiers and would otherwise need an arbitrary owner.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Combinations</em>' containment reference list.
	 * @see org.eclipse.fennec.model.compliance.report.ReportPackage#getComplianceReport_Combinations()
	 * @model containment="true"
	 * @generated
	 */
	EList<CombinationFinding> getCombinations();

	/**
	 * Returns the value of the '<em><b>Disclaimer</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Statement of what the report is and is not. It is decision support for a data protection officer: it flags features needing human review and must not assert compliance or non-compliance.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Disclaimer</em>' attribute.
	 * @see #setDisclaimer(String)
	 * @see org.eclipse.fennec.model.compliance.report.ReportPackage#getComplianceReport_Disclaimer()
	 * @model
	 * @generated
	 */
	String getDisclaimer();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getDisclaimer <em>Disclaimer</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Disclaimer</em>' attribute.
	 * @see #getDisclaimer()
	 * @generated
	 */
	void setDisclaimer(String value);

	/**
	 * Returns the value of the '<em><b>Origin</b></em>' attribute.
	 * The literals are from the enumeration {@link org.eclipse.fennec.model.compliance.report.ReportOrigin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * The origin of the report, namely whether it was redacted by an AI agent or by a human
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Origin</em>' attribute.
	 * @see org.eclipse.fennec.model.compliance.report.ReportOrigin
	 * @see #setOrigin(ReportOrigin)
	 * @see org.eclipse.fennec.model.compliance.report.ReportPackage#getComplianceReport_Origin()
	 * @model
	 * @generated
	 */
	ReportOrigin getOrigin();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.compliance.report.ComplianceReport#getOrigin <em>Origin</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Origin</em>' attribute.
	 * @see org.eclipse.fennec.model.compliance.report.ReportOrigin
	 * @see #getOrigin()
	 * @generated
	 */
	void setOrigin(ReportOrigin value);

	/**
	 * Returns the value of the '<em><b>Contexts</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.fennec.model.compliance.context.ContextRef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * The contexts, pinned to the version the subject was checked against.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Contexts</em>' containment reference list.
	 * @see org.eclipse.fennec.model.compliance.report.ReportPackage#getComplianceReport_Contexts()
	 * @model containment="true" required="true"
	 * @generated
	 */
	EList<ContextRef> getContexts();

} // ComplianceReport
