/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 * 
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Data In Motion Consulting - initial implementation
 */
package org.eclipse.fennec.model.gdprReportHistory.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.fennec.model.gdprReportHistory.GDPRReportHistoryPackage;
import org.eclipse.fennec.model.gdprReportHistory.ReportRevision;
import org.eclipse.fennec.model.gdprReportHistory.RevisionOrigin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Report Revision</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.impl.ReportRevisionImpl#getRevisionNumber <em>Revision Number</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.impl.ReportRevisionImpl#getReportId <em>Report Id</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.impl.ReportRevisionImpl#getModelFingerprint <em>Model Fingerprint</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.impl.ReportRevisionImpl#getGeneratedAt <em>Generated At</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.impl.ReportRevisionImpl#getGeneratedBy <em>Generated By</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.impl.ReportRevisionImpl#getOrigin <em>Origin</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.impl.ReportRevisionImpl#getCorpusCelex <em>Corpus Celex</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.impl.ReportRevisionImpl#getCorpusConsolidatedDate <em>Corpus Consolidated Date</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.impl.ReportRevisionImpl#getFindingCount <em>Finding Count</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.impl.ReportRevisionImpl#getChangeCount <em>Change Count</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReportRevisionImpl extends MinimalEObjectImpl.Container implements ReportRevision {
	/**
	 * The default value of the '{@link #getRevisionNumber() <em>Revision Number</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRevisionNumber()
	 * @generated
	 * @ordered
	 */
	protected static final int REVISION_NUMBER_EDEFAULT = 0;

	/**
	 * The cached value of the '{@link #getRevisionNumber() <em>Revision Number</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRevisionNumber()
	 * @generated
	 * @ordered
	 */
	protected int revisionNumber = REVISION_NUMBER_EDEFAULT;

	/**
	 * The default value of the '{@link #getReportId() <em>Report Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getReportId()
	 * @generated
	 * @ordered
	 */
	protected static final String REPORT_ID_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getReportId() <em>Report Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getReportId()
	 * @generated
	 * @ordered
	 */
	protected String reportId = REPORT_ID_EDEFAULT;

	/**
	 * The default value of the '{@link #getModelFingerprint() <em>Model Fingerprint</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getModelFingerprint()
	 * @generated
	 * @ordered
	 */
	protected static final String MODEL_FINGERPRINT_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getModelFingerprint() <em>Model Fingerprint</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getModelFingerprint()
	 * @generated
	 * @ordered
	 */
	protected String modelFingerprint = MODEL_FINGERPRINT_EDEFAULT;

	/**
	 * The default value of the '{@link #getGeneratedAt() <em>Generated At</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedAt()
	 * @generated
	 * @ordered
	 */
	protected static final String GENERATED_AT_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getGeneratedAt() <em>Generated At</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedAt()
	 * @generated
	 * @ordered
	 */
	protected String generatedAt = GENERATED_AT_EDEFAULT;

	/**
	 * The default value of the '{@link #getGeneratedBy() <em>Generated By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected static final String GENERATED_BY_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getGeneratedBy() <em>Generated By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected String generatedBy = GENERATED_BY_EDEFAULT;

	/**
	 * The default value of the '{@link #getOrigin() <em>Origin</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOrigin()
	 * @generated
	 * @ordered
	 */
	protected static final RevisionOrigin ORIGIN_EDEFAULT = RevisionOrigin.UNKNOWN;

	/**
	 * The cached value of the '{@link #getOrigin() <em>Origin</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOrigin()
	 * @generated
	 * @ordered
	 */
	protected RevisionOrigin origin = ORIGIN_EDEFAULT;

	/**
	 * The default value of the '{@link #getCorpusCelex() <em>Corpus Celex</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getCorpusCelex()
	 * @generated
	 * @ordered
	 */
	protected static final String CORPUS_CELEX_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getCorpusCelex() <em>Corpus Celex</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getCorpusCelex()
	 * @generated
	 * @ordered
	 */
	protected String corpusCelex = CORPUS_CELEX_EDEFAULT;

	/**
	 * The default value of the '{@link #getCorpusConsolidatedDate() <em>Corpus Consolidated Date</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getCorpusConsolidatedDate()
	 * @generated
	 * @ordered
	 */
	protected static final String CORPUS_CONSOLIDATED_DATE_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getCorpusConsolidatedDate() <em>Corpus Consolidated Date</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getCorpusConsolidatedDate()
	 * @generated
	 * @ordered
	 */
	protected String corpusConsolidatedDate = CORPUS_CONSOLIDATED_DATE_EDEFAULT;

	/**
	 * The default value of the '{@link #getFindingCount() <em>Finding Count</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getFindingCount()
	 * @generated
	 * @ordered
	 */
	protected static final int FINDING_COUNT_EDEFAULT = 0;

	/**
	 * The cached value of the '{@link #getFindingCount() <em>Finding Count</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getFindingCount()
	 * @generated
	 * @ordered
	 */
	protected int findingCount = FINDING_COUNT_EDEFAULT;

	/**
	 * The default value of the '{@link #getChangeCount() <em>Change Count</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getChangeCount()
	 * @generated
	 * @ordered
	 */
	protected static final int CHANGE_COUNT_EDEFAULT = 0;

	/**
	 * The cached value of the '{@link #getChangeCount() <em>Change Count</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getChangeCount()
	 * @generated
	 * @ordered
	 */
	protected int changeCount = CHANGE_COUNT_EDEFAULT;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReportRevisionImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return GDPRReportHistoryPackage.Literals.REPORT_REVISION;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public int getRevisionNumber() {
		return revisionNumber;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setRevisionNumber(int newRevisionNumber) {
		int oldRevisionNumber = revisionNumber;
		revisionNumber = newRevisionNumber;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportHistoryPackage.REPORT_REVISION__REVISION_NUMBER, oldRevisionNumber, revisionNumber));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getReportId() {
		return reportId;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setReportId(String newReportId) {
		String oldReportId = reportId;
		reportId = newReportId;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportHistoryPackage.REPORT_REVISION__REPORT_ID, oldReportId, reportId));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getModelFingerprint() {
		return modelFingerprint;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setModelFingerprint(String newModelFingerprint) {
		String oldModelFingerprint = modelFingerprint;
		modelFingerprint = newModelFingerprint;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportHistoryPackage.REPORT_REVISION__MODEL_FINGERPRINT, oldModelFingerprint, modelFingerprint));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getGeneratedAt() {
		return generatedAt;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setGeneratedAt(String newGeneratedAt) {
		String oldGeneratedAt = generatedAt;
		generatedAt = newGeneratedAt;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportHistoryPackage.REPORT_REVISION__GENERATED_AT, oldGeneratedAt, generatedAt));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getGeneratedBy() {
		return generatedBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setGeneratedBy(String newGeneratedBy) {
		String oldGeneratedBy = generatedBy;
		generatedBy = newGeneratedBy;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportHistoryPackage.REPORT_REVISION__GENERATED_BY, oldGeneratedBy, generatedBy));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public RevisionOrigin getOrigin() {
		return origin;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setOrigin(RevisionOrigin newOrigin) {
		RevisionOrigin oldOrigin = origin;
		origin = newOrigin == null ? ORIGIN_EDEFAULT : newOrigin;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportHistoryPackage.REPORT_REVISION__ORIGIN, oldOrigin, origin));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getCorpusCelex() {
		return corpusCelex;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setCorpusCelex(String newCorpusCelex) {
		String oldCorpusCelex = corpusCelex;
		corpusCelex = newCorpusCelex;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportHistoryPackage.REPORT_REVISION__CORPUS_CELEX, oldCorpusCelex, corpusCelex));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getCorpusConsolidatedDate() {
		return corpusConsolidatedDate;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setCorpusConsolidatedDate(String newCorpusConsolidatedDate) {
		String oldCorpusConsolidatedDate = corpusConsolidatedDate;
		corpusConsolidatedDate = newCorpusConsolidatedDate;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportHistoryPackage.REPORT_REVISION__CORPUS_CONSOLIDATED_DATE, oldCorpusConsolidatedDate, corpusConsolidatedDate));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public int getFindingCount() {
		return findingCount;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setFindingCount(int newFindingCount) {
		int oldFindingCount = findingCount;
		findingCount = newFindingCount;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportHistoryPackage.REPORT_REVISION__FINDING_COUNT, oldFindingCount, findingCount));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public int getChangeCount() {
		return changeCount;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setChangeCount(int newChangeCount) {
		int oldChangeCount = changeCount;
		changeCount = newChangeCount;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportHistoryPackage.REPORT_REVISION__CHANGE_COUNT, oldChangeCount, changeCount));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case GDPRReportHistoryPackage.REPORT_REVISION__REVISION_NUMBER:
				return getRevisionNumber();
			case GDPRReportHistoryPackage.REPORT_REVISION__REPORT_ID:
				return getReportId();
			case GDPRReportHistoryPackage.REPORT_REVISION__MODEL_FINGERPRINT:
				return getModelFingerprint();
			case GDPRReportHistoryPackage.REPORT_REVISION__GENERATED_AT:
				return getGeneratedAt();
			case GDPRReportHistoryPackage.REPORT_REVISION__GENERATED_BY:
				return getGeneratedBy();
			case GDPRReportHistoryPackage.REPORT_REVISION__ORIGIN:
				return getOrigin();
			case GDPRReportHistoryPackage.REPORT_REVISION__CORPUS_CELEX:
				return getCorpusCelex();
			case GDPRReportHistoryPackage.REPORT_REVISION__CORPUS_CONSOLIDATED_DATE:
				return getCorpusConsolidatedDate();
			case GDPRReportHistoryPackage.REPORT_REVISION__FINDING_COUNT:
				return getFindingCount();
			case GDPRReportHistoryPackage.REPORT_REVISION__CHANGE_COUNT:
				return getChangeCount();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case GDPRReportHistoryPackage.REPORT_REVISION__REVISION_NUMBER:
				setRevisionNumber((Integer)newValue);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__REPORT_ID:
				setReportId((String)newValue);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__MODEL_FINGERPRINT:
				setModelFingerprint((String)newValue);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__GENERATED_AT:
				setGeneratedAt((String)newValue);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__GENERATED_BY:
				setGeneratedBy((String)newValue);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__ORIGIN:
				setOrigin((RevisionOrigin)newValue);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__CORPUS_CELEX:
				setCorpusCelex((String)newValue);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__CORPUS_CONSOLIDATED_DATE:
				setCorpusConsolidatedDate((String)newValue);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__FINDING_COUNT:
				setFindingCount((Integer)newValue);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__CHANGE_COUNT:
				setChangeCount((Integer)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case GDPRReportHistoryPackage.REPORT_REVISION__REVISION_NUMBER:
				setRevisionNumber(REVISION_NUMBER_EDEFAULT);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__REPORT_ID:
				setReportId(REPORT_ID_EDEFAULT);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__MODEL_FINGERPRINT:
				setModelFingerprint(MODEL_FINGERPRINT_EDEFAULT);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__GENERATED_AT:
				setGeneratedAt(GENERATED_AT_EDEFAULT);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__GENERATED_BY:
				setGeneratedBy(GENERATED_BY_EDEFAULT);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__ORIGIN:
				setOrigin(ORIGIN_EDEFAULT);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__CORPUS_CELEX:
				setCorpusCelex(CORPUS_CELEX_EDEFAULT);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__CORPUS_CONSOLIDATED_DATE:
				setCorpusConsolidatedDate(CORPUS_CONSOLIDATED_DATE_EDEFAULT);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__FINDING_COUNT:
				setFindingCount(FINDING_COUNT_EDEFAULT);
				return;
			case GDPRReportHistoryPackage.REPORT_REVISION__CHANGE_COUNT:
				setChangeCount(CHANGE_COUNT_EDEFAULT);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case GDPRReportHistoryPackage.REPORT_REVISION__REVISION_NUMBER:
				return revisionNumber != REVISION_NUMBER_EDEFAULT;
			case GDPRReportHistoryPackage.REPORT_REVISION__REPORT_ID:
				return REPORT_ID_EDEFAULT == null ? reportId != null : !REPORT_ID_EDEFAULT.equals(reportId);
			case GDPRReportHistoryPackage.REPORT_REVISION__MODEL_FINGERPRINT:
				return MODEL_FINGERPRINT_EDEFAULT == null ? modelFingerprint != null : !MODEL_FINGERPRINT_EDEFAULT.equals(modelFingerprint);
			case GDPRReportHistoryPackage.REPORT_REVISION__GENERATED_AT:
				return GENERATED_AT_EDEFAULT == null ? generatedAt != null : !GENERATED_AT_EDEFAULT.equals(generatedAt);
			case GDPRReportHistoryPackage.REPORT_REVISION__GENERATED_BY:
				return GENERATED_BY_EDEFAULT == null ? generatedBy != null : !GENERATED_BY_EDEFAULT.equals(generatedBy);
			case GDPRReportHistoryPackage.REPORT_REVISION__ORIGIN:
				return origin != ORIGIN_EDEFAULT;
			case GDPRReportHistoryPackage.REPORT_REVISION__CORPUS_CELEX:
				return CORPUS_CELEX_EDEFAULT == null ? corpusCelex != null : !CORPUS_CELEX_EDEFAULT.equals(corpusCelex);
			case GDPRReportHistoryPackage.REPORT_REVISION__CORPUS_CONSOLIDATED_DATE:
				return CORPUS_CONSOLIDATED_DATE_EDEFAULT == null ? corpusConsolidatedDate != null : !CORPUS_CONSOLIDATED_DATE_EDEFAULT.equals(corpusConsolidatedDate);
			case GDPRReportHistoryPackage.REPORT_REVISION__FINDING_COUNT:
				return findingCount != FINDING_COUNT_EDEFAULT;
			case GDPRReportHistoryPackage.REPORT_REVISION__CHANGE_COUNT:
				return changeCount != CHANGE_COUNT_EDEFAULT;
		}
		return super.eIsSet(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String toString() {
		if (eIsProxy()) return super.toString();

		StringBuilder result = new StringBuilder(super.toString());
		result.append(" (revisionNumber: ");
		result.append(revisionNumber);
		result.append(", reportId: ");
		result.append(reportId);
		result.append(", modelFingerprint: ");
		result.append(modelFingerprint);
		result.append(", generatedAt: ");
		result.append(generatedAt);
		result.append(", generatedBy: ");
		result.append(generatedBy);
		result.append(", origin: ");
		result.append(origin);
		result.append(", corpusCelex: ");
		result.append(corpusCelex);
		result.append(", corpusConsolidatedDate: ");
		result.append(corpusConsolidatedDate);
		result.append(", findingCount: ");
		result.append(findingCount);
		result.append(", changeCount: ");
		result.append(changeCount);
		result.append(')');
		return result.toString();
	}

} //ReportRevisionImpl
