/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 * 
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Data In Motion Consulting - initial implementation
 */
package org.eclipse.fennec.model.gdprReportHistory;

import org.eclipse.emf.ecore.EObject;

import org.osgi.annotation.versioning.ProviderType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Report Revision</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * One review run of the subject - an agent review or a human correction - as a single spreadsheet row.
 * <!-- end-model-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getRevisionNumber <em>Revision Number</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getReportId <em>Report Id</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getModelFingerprint <em>Model Fingerprint</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getGeneratedAt <em>Generated At</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getGeneratedBy <em>Generated By</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getOrigin <em>Origin</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getCorpusCelex <em>Corpus Celex</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getCorpusConsolidatedDate <em>Corpus Consolidated Date</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getFindingCount <em>Finding Count</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getChangeCount <em>Change Count</em>}</li>
 * </ul>
 *
 * @see org.eclipse.fennec.model.gdprReportHistory.GDPRReportHistoryPackage#getReportRevision()
 * @model
 * @generated
 */
@ProviderType
public interface ReportRevision extends EObject {
	/**
	 * Returns the value of the '<em><b>Revision Number</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * 1-based position in chronological order. The join key the other two sheets point at.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Revision Number</em>' attribute.
	 * @see #setRevisionNumber(int)
	 * @see org.eclipse.fennec.model.gdprReportHistory.GDPRReportHistoryPackage#getReportRevision_RevisionNumber()
	 * @model required="true"
	 * @generated
	 */
	int getRevisionNumber();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getRevisionNumber <em>Revision Number</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Revision Number</em>' attribute.
	 * @see #getRevisionNumber()
	 * @generated
	 */
	void setRevisionNumber(int value);

	/**
	 * Returns the value of the '<em><b>Report Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Identifier of the stored GdprReport this revision was read from, so a row in the document can be traced back to the sealed report it summarises.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Report Id</em>' attribute.
	 * @see #setReportId(String)
	 * @see org.eclipse.fennec.model.gdprReportHistory.GDPRReportHistoryPackage#getReportRevision_ReportId()
	 * @model required="true"
	 * @generated
	 */
	String getReportId();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getReportId <em>Report Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Report Id</em>' attribute.
	 * @see #getReportId()
	 * @generated
	 */
	void setReportId(String value);

	/**
	 * Returns the value of the '<em><b>Model Fingerprint</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Fingerprint of the subject as this revision reviewed it. Equal to the root's fingerprint while a document covers one revision of the model; the column is what lets a document later span several.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Model Fingerprint</em>' attribute.
	 * @see #setModelFingerprint(String)
	 * @see org.eclipse.fennec.model.gdprReportHistory.GDPRReportHistoryPackage#getReportRevision_ModelFingerprint()
	 * @model
	 * @generated
	 */
	String getModelFingerprint();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getModelFingerprint <em>Model Fingerprint</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Model Fingerprint</em>' attribute.
	 * @see #getModelFingerprint()
	 * @generated
	 */
	void setModelFingerprint(String value);

	/**
	 * Returns the value of the '<em><b>Generated At</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * When the review was produced, copied from GdprReport.generatedAt. Orders the revisions; a missing or unparsable value falls back to the timestamp in the report id.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Generated At</em>' attribute.
	 * @see #setGeneratedAt(String)
	 * @see org.eclipse.fennec.model.gdprReportHistory.GDPRReportHistoryPackage#getReportRevision_GeneratedAt()
	 * @model
	 * @generated
	 */
	String getGeneratedAt();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getGeneratedAt <em>Generated At</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Generated At</em>' attribute.
	 * @see #getGeneratedAt()
	 * @generated
	 */
	void setGeneratedAt(String value);

	/**
	 * Returns the value of the '<em><b>Generated By</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Who or what produced the review, copied from GdprReport.generatedBy - a model identifier for an agent run, a user for a correction.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Generated By</em>' attribute.
	 * @see #setGeneratedBy(String)
	 * @see org.eclipse.fennec.model.gdprReportHistory.GDPRReportHistoryPackage#getReportRevision_GeneratedBy()
	 * @model
	 * @generated
	 */
	String getGeneratedBy();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getGeneratedBy <em>Generated By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Generated By</em>' attribute.
	 * @see #getGeneratedBy()
	 * @generated
	 */
	void setGeneratedBy(String value);

	/**
	 * Returns the value of the '<em><b>Origin</b></em>' attribute.
	 * The literals are from the enumeration {@link org.eclipse.fennec.model.gdprReportHistory.RevisionOrigin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Whether this revision came from an agent review or from a human editing an earlier one. The column a compliance reader looks at first, because it says who is accountable for the verdict.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Origin</em>' attribute.
	 * @see org.eclipse.fennec.model.gdprReportHistory.RevisionOrigin
	 * @see #setOrigin(RevisionOrigin)
	 * @see org.eclipse.fennec.model.gdprReportHistory.GDPRReportHistoryPackage#getReportRevision_Origin()
	 * @model
	 * @generated
	 */
	RevisionOrigin getOrigin();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getOrigin <em>Origin</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Origin</em>' attribute.
	 * @see org.eclipse.fennec.model.gdprReportHistory.RevisionOrigin
	 * @see #getOrigin()
	 * @generated
	 */
	void setOrigin(RevisionOrigin value);

	/**
	 * Returns the value of the '<em><b>Corpus Celex</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * CELEX number of the legal corpus the review cited, copied from LegalCorpusRef.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Corpus Celex</em>' attribute.
	 * @see #setCorpusCelex(String)
	 * @see org.eclipse.fennec.model.gdprReportHistory.GDPRReportHistoryPackage#getReportRevision_CorpusCelex()
	 * @model
	 * @generated
	 */
	String getCorpusCelex();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getCorpusCelex <em>Corpus Celex</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Corpus Celex</em>' attribute.
	 * @see #getCorpusCelex()
	 * @generated
	 */
	void setCorpusCelex(String value);

	/**
	 * Returns the value of the '<em><b>Corpus Consolidated Date</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Consolidation date of that corpus. Carried per revision because a verdict is only meaningful against the text it was checked on: two revisions may differ because the law moved, not because the model did.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Corpus Consolidated Date</em>' attribute.
	 * @see #setCorpusConsolidatedDate(String)
	 * @see org.eclipse.fennec.model.gdprReportHistory.GDPRReportHistoryPackage#getReportRevision_CorpusConsolidatedDate()
	 * @model
	 * @generated
	 */
	String getCorpusConsolidatedDate();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getCorpusConsolidatedDate <em>Corpus Consolidated Date</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Corpus Consolidated Date</em>' attribute.
	 * @see #getCorpusConsolidatedDate()
	 * @generated
	 */
	void setCorpusConsolidatedDate(String value);

	/**
	 * Returns the value of the '<em><b>Finding Count</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Number of findings recorded in this revision.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Finding Count</em>' attribute.
	 * @see #setFindingCount(int)
	 * @see org.eclipse.fennec.model.gdprReportHistory.GDPRReportHistoryPackage#getReportRevision_FindingCount()
	 * @model
	 * @generated
	 */
	int getFindingCount();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getFindingCount <em>Finding Count</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Finding Count</em>' attribute.
	 * @see #getFindingCount()
	 * @generated
	 */
	void setFindingCount(int value);

	/**
	 * Returns the value of the '<em><b>Change Count</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Number of change rows attributed to this revision. Zero on the first revision, which has nothing to differ from.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Change Count</em>' attribute.
	 * @see #setChangeCount(int)
	 * @see org.eclipse.fennec.model.gdprReportHistory.GDPRReportHistoryPackage#getReportRevision_ChangeCount()
	 * @model
	 * @generated
	 */
	int getChangeCount();

	/**
	 * Sets the value of the '{@link org.eclipse.fennec.model.gdprReportHistory.ReportRevision#getChangeCount <em>Change Count</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Change Count</em>' attribute.
	 * @see #getChangeCount()
	 * @generated
	 */
	void setChangeCount(int value);

} // ReportRevision
