/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 * 
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Data In Motion Consulting - initial implementation
 */
package org.eclipse.fennec.model.gdprReport.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.eclipse.fennec.model.gdprReport.ClassifierEvaluation;
import org.eclipse.fennec.model.gdprReport.CombinationFinding;
import org.eclipse.fennec.model.gdprReport.GDPRReportPackage;
import org.eclipse.fennec.model.gdprReport.GdprReport;
import org.eclipse.fennec.model.gdprReport.GdprReportOrigin;
import org.eclipse.fennec.model.gdprReport.LegalCorpusRef;
import org.eclipse.fennec.model.gdprReport.SubjectModel;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Gdpr Report</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.impl.GdprReportImpl#getReportId <em>Report Id</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.impl.GdprReportImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.impl.GdprReportImpl#getGeneratedAt <em>Generated At</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.impl.GdprReportImpl#getGeneratedBy <em>Generated By</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.impl.GdprReportImpl#getSubject <em>Subject</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.impl.GdprReportImpl#getCorpus <em>Corpus</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.impl.GdprReportImpl#getClassifierEvaluation <em>Classifier Evaluation</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.impl.GdprReportImpl#getCombinations <em>Combinations</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.impl.GdprReportImpl#getDisclaimer <em>Disclaimer</em>}</li>
 *   <li>{@link org.eclipse.fennec.model.gdprReport.impl.GdprReportImpl#getOrigin <em>Origin</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GdprReportImpl extends MinimalEObjectImpl.Container implements GdprReport {
	/**
	 * The default value of the '{@link #getReportId() <em>Report Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getReportId()
	 * @generated
	 * @ordered
	 */
	protected static final String REPORT_ID_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getReportId() <em>Report Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getReportId()
	 * @generated
	 * @ordered
	 */
	protected String reportId = REPORT_ID_EDEFAULT;

	/**
	 * The default value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
	protected static final String NAME_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
	protected String name = NAME_EDEFAULT;

	/**
	 * The default value of the '{@link #getGeneratedAt() <em>Generated At</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedAt()
	 * @generated
	 * @ordered
	 */
	protected static final String GENERATED_AT_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getGeneratedAt() <em>Generated At</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedAt()
	 * @generated
	 * @ordered
	 */
	protected String generatedAt = GENERATED_AT_EDEFAULT;

	/**
	 * The default value of the '{@link #getGeneratedBy() <em>Generated By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected static final String GENERATED_BY_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getGeneratedBy() <em>Generated By</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected String generatedBy = GENERATED_BY_EDEFAULT;

	/**
	 * The cached value of the '{@link #getSubject() <em>Subject</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getSubject()
	 * @generated
	 * @ordered
	 */
	protected SubjectModel subject;

	/**
	 * The cached value of the '{@link #getCorpus() <em>Corpus</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getCorpus()
	 * @generated
	 * @ordered
	 */
	protected LegalCorpusRef corpus;

	/**
	 * The cached value of the '{@link #getClassifierEvaluation() <em>Classifier Evaluation</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getClassifierEvaluation()
	 * @generated
	 * @ordered
	 */
	protected EList<ClassifierEvaluation> classifierEvaluation;

	/**
	 * The cached value of the '{@link #getCombinations() <em>Combinations</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getCombinations()
	 * @generated
	 * @ordered
	 */
	protected EList<CombinationFinding> combinations;

	/**
	 * The default value of the '{@link #getDisclaimer() <em>Disclaimer</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDisclaimer()
	 * @generated
	 * @ordered
	 */
	protected static final String DISCLAIMER_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getDisclaimer() <em>Disclaimer</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDisclaimer()
	 * @generated
	 * @ordered
	 */
	protected String disclaimer = DISCLAIMER_EDEFAULT;

	/**
	 * The default value of the '{@link #getOrigin() <em>Origin</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOrigin()
	 * @generated
	 * @ordered
	 */
	protected static final GdprReportOrigin ORIGIN_EDEFAULT = GdprReportOrigin.UNKNOWN;

	/**
	 * The cached value of the '{@link #getOrigin() <em>Origin</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOrigin()
	 * @generated
	 * @ordered
	 */
	protected GdprReportOrigin origin = ORIGIN_EDEFAULT;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GdprReportImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return GDPRReportPackage.Literals.GDPR_REPORT;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getReportId() {
		return reportId;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setReportId(String newReportId) {
		String oldReportId = reportId;
		reportId = newReportId;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportPackage.GDPR_REPORT__REPORT_ID, oldReportId, reportId));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getName() {
		return name;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setName(String newName) {
		String oldName = name;
		name = newName;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportPackage.GDPR_REPORT__NAME, oldName, name));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getGeneratedAt() {
		return generatedAt;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setGeneratedAt(String newGeneratedAt) {
		String oldGeneratedAt = generatedAt;
		generatedAt = newGeneratedAt;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportPackage.GDPR_REPORT__GENERATED_AT, oldGeneratedAt, generatedAt));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getGeneratedBy() {
		return generatedBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setGeneratedBy(String newGeneratedBy) {
		String oldGeneratedBy = generatedBy;
		generatedBy = newGeneratedBy;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportPackage.GDPR_REPORT__GENERATED_BY, oldGeneratedBy, generatedBy));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public SubjectModel getSubject() {
		return subject;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetSubject(SubjectModel newSubject, NotificationChain msgs) {
		SubjectModel oldSubject = subject;
		subject = newSubject;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GDPRReportPackage.GDPR_REPORT__SUBJECT, oldSubject, newSubject);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setSubject(SubjectModel newSubject) {
		if (newSubject != subject) {
			NotificationChain msgs = null;
			if (subject != null)
				msgs = ((InternalEObject)subject).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GDPRReportPackage.GDPR_REPORT__SUBJECT, null, msgs);
			if (newSubject != null)
				msgs = ((InternalEObject)newSubject).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GDPRReportPackage.GDPR_REPORT__SUBJECT, null, msgs);
			msgs = basicSetSubject(newSubject, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportPackage.GDPR_REPORT__SUBJECT, newSubject, newSubject));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public LegalCorpusRef getCorpus() {
		return corpus;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetCorpus(LegalCorpusRef newCorpus, NotificationChain msgs) {
		LegalCorpusRef oldCorpus = corpus;
		corpus = newCorpus;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GDPRReportPackage.GDPR_REPORT__CORPUS, oldCorpus, newCorpus);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setCorpus(LegalCorpusRef newCorpus) {
		if (newCorpus != corpus) {
			NotificationChain msgs = null;
			if (corpus != null)
				msgs = ((InternalEObject)corpus).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GDPRReportPackage.GDPR_REPORT__CORPUS, null, msgs);
			if (newCorpus != null)
				msgs = ((InternalEObject)newCorpus).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GDPRReportPackage.GDPR_REPORT__CORPUS, null, msgs);
			msgs = basicSetCorpus(newCorpus, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportPackage.GDPR_REPORT__CORPUS, newCorpus, newCorpus));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<ClassifierEvaluation> getClassifierEvaluation() {
		if (classifierEvaluation == null) {
			classifierEvaluation = new EObjectContainmentEList<ClassifierEvaluation>(ClassifierEvaluation.class, this, GDPRReportPackage.GDPR_REPORT__CLASSIFIER_EVALUATION);
		}
		return classifierEvaluation;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<CombinationFinding> getCombinations() {
		if (combinations == null) {
			combinations = new EObjectContainmentEList<CombinationFinding>(CombinationFinding.class, this, GDPRReportPackage.GDPR_REPORT__COMBINATIONS);
		}
		return combinations;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getDisclaimer() {
		return disclaimer;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setDisclaimer(String newDisclaimer) {
		String oldDisclaimer = disclaimer;
		disclaimer = newDisclaimer;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportPackage.GDPR_REPORT__DISCLAIMER, oldDisclaimer, disclaimer));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public GdprReportOrigin getOrigin() {
		return origin;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setOrigin(GdprReportOrigin newOrigin) {
		GdprReportOrigin oldOrigin = origin;
		origin = newOrigin == null ? ORIGIN_EDEFAULT : newOrigin;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, GDPRReportPackage.GDPR_REPORT__ORIGIN, oldOrigin, origin));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case GDPRReportPackage.GDPR_REPORT__SUBJECT:
				return basicSetSubject(null, msgs);
			case GDPRReportPackage.GDPR_REPORT__CORPUS:
				return basicSetCorpus(null, msgs);
			case GDPRReportPackage.GDPR_REPORT__CLASSIFIER_EVALUATION:
				return ((InternalEList<?>)getClassifierEvaluation()).basicRemove(otherEnd, msgs);
			case GDPRReportPackage.GDPR_REPORT__COMBINATIONS:
				return ((InternalEList<?>)getCombinations()).basicRemove(otherEnd, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case GDPRReportPackage.GDPR_REPORT__REPORT_ID:
				return getReportId();
			case GDPRReportPackage.GDPR_REPORT__NAME:
				return getName();
			case GDPRReportPackage.GDPR_REPORT__GENERATED_AT:
				return getGeneratedAt();
			case GDPRReportPackage.GDPR_REPORT__GENERATED_BY:
				return getGeneratedBy();
			case GDPRReportPackage.GDPR_REPORT__SUBJECT:
				return getSubject();
			case GDPRReportPackage.GDPR_REPORT__CORPUS:
				return getCorpus();
			case GDPRReportPackage.GDPR_REPORT__CLASSIFIER_EVALUATION:
				return getClassifierEvaluation();
			case GDPRReportPackage.GDPR_REPORT__COMBINATIONS:
				return getCombinations();
			case GDPRReportPackage.GDPR_REPORT__DISCLAIMER:
				return getDisclaimer();
			case GDPRReportPackage.GDPR_REPORT__ORIGIN:
				return getOrigin();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case GDPRReportPackage.GDPR_REPORT__REPORT_ID:
				setReportId((String)newValue);
				return;
			case GDPRReportPackage.GDPR_REPORT__NAME:
				setName((String)newValue);
				return;
			case GDPRReportPackage.GDPR_REPORT__GENERATED_AT:
				setGeneratedAt((String)newValue);
				return;
			case GDPRReportPackage.GDPR_REPORT__GENERATED_BY:
				setGeneratedBy((String)newValue);
				return;
			case GDPRReportPackage.GDPR_REPORT__SUBJECT:
				setSubject((SubjectModel)newValue);
				return;
			case GDPRReportPackage.GDPR_REPORT__CORPUS:
				setCorpus((LegalCorpusRef)newValue);
				return;
			case GDPRReportPackage.GDPR_REPORT__CLASSIFIER_EVALUATION:
				getClassifierEvaluation().clear();
				getClassifierEvaluation().addAll((Collection<? extends ClassifierEvaluation>)newValue);
				return;
			case GDPRReportPackage.GDPR_REPORT__COMBINATIONS:
				getCombinations().clear();
				getCombinations().addAll((Collection<? extends CombinationFinding>)newValue);
				return;
			case GDPRReportPackage.GDPR_REPORT__DISCLAIMER:
				setDisclaimer((String)newValue);
				return;
			case GDPRReportPackage.GDPR_REPORT__ORIGIN:
				setOrigin((GdprReportOrigin)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case GDPRReportPackage.GDPR_REPORT__REPORT_ID:
				setReportId(REPORT_ID_EDEFAULT);
				return;
			case GDPRReportPackage.GDPR_REPORT__NAME:
				setName(NAME_EDEFAULT);
				return;
			case GDPRReportPackage.GDPR_REPORT__GENERATED_AT:
				setGeneratedAt(GENERATED_AT_EDEFAULT);
				return;
			case GDPRReportPackage.GDPR_REPORT__GENERATED_BY:
				setGeneratedBy(GENERATED_BY_EDEFAULT);
				return;
			case GDPRReportPackage.GDPR_REPORT__SUBJECT:
				setSubject((SubjectModel)null);
				return;
			case GDPRReportPackage.GDPR_REPORT__CORPUS:
				setCorpus((LegalCorpusRef)null);
				return;
			case GDPRReportPackage.GDPR_REPORT__CLASSIFIER_EVALUATION:
				getClassifierEvaluation().clear();
				return;
			case GDPRReportPackage.GDPR_REPORT__COMBINATIONS:
				getCombinations().clear();
				return;
			case GDPRReportPackage.GDPR_REPORT__DISCLAIMER:
				setDisclaimer(DISCLAIMER_EDEFAULT);
				return;
			case GDPRReportPackage.GDPR_REPORT__ORIGIN:
				setOrigin(ORIGIN_EDEFAULT);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case GDPRReportPackage.GDPR_REPORT__REPORT_ID:
				return REPORT_ID_EDEFAULT == null ? reportId != null : !REPORT_ID_EDEFAULT.equals(reportId);
			case GDPRReportPackage.GDPR_REPORT__NAME:
				return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
			case GDPRReportPackage.GDPR_REPORT__GENERATED_AT:
				return GENERATED_AT_EDEFAULT == null ? generatedAt != null : !GENERATED_AT_EDEFAULT.equals(generatedAt);
			case GDPRReportPackage.GDPR_REPORT__GENERATED_BY:
				return GENERATED_BY_EDEFAULT == null ? generatedBy != null : !GENERATED_BY_EDEFAULT.equals(generatedBy);
			case GDPRReportPackage.GDPR_REPORT__SUBJECT:
				return subject != null;
			case GDPRReportPackage.GDPR_REPORT__CORPUS:
				return corpus != null;
			case GDPRReportPackage.GDPR_REPORT__CLASSIFIER_EVALUATION:
				return classifierEvaluation != null && !classifierEvaluation.isEmpty();
			case GDPRReportPackage.GDPR_REPORT__COMBINATIONS:
				return combinations != null && !combinations.isEmpty();
			case GDPRReportPackage.GDPR_REPORT__DISCLAIMER:
				return DISCLAIMER_EDEFAULT == null ? disclaimer != null : !DISCLAIMER_EDEFAULT.equals(disclaimer);
			case GDPRReportPackage.GDPR_REPORT__ORIGIN:
				return origin != ORIGIN_EDEFAULT;
		}
		return super.eIsSet(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String toString() {
		if (eIsProxy()) return super.toString();

		StringBuilder result = new StringBuilder(super.toString());
		result.append(" (reportId: ");
		result.append(reportId);
		result.append(", name: ");
		result.append(name);
		result.append(", generatedAt: ");
		result.append(generatedAt);
		result.append(", generatedBy: ");
		result.append(generatedBy);
		result.append(", disclaimer: ");
		result.append(disclaimer);
		result.append(", origin: ");
		result.append(origin);
		result.append(')');
		return result.toString();
	}

} //GdprReportImpl
